package org.academiadecodigo.codezillas.converters;

public enum Airports {
    LCG("A Coruña Airport","A Coruña"),
    AAH("Merzbrück Airport","Aachen"),
    AAL("Aalborg Airport","Aalborg"),
    AAR("Aarhus Airport","Aarhus"),
    ABZ("Aberdeen Airport","Aberdeen"),
    AGF("Agen La Garenne Airport","Agen"),
    AGQ("Agrinion Airport","Agrinion"),
    AJA("Ajaccio Napoleon Bonaparte Airport","Ajaccio"),
    AKT("RAF Akrotiri","Akrotiri"),
    ABC("Albacete Airport","Albacete"),
    ALL("Albenga Airport","Albenga"),
    BYF("Albert – Picardie Airport[1]","Albert"),
    LBI("Le Sequestre Airport","Albi"),
    ACI("Alderney Airport","Alderney"),
    AES("Ålesund Airport, Vigra","Ålesund"),
    AXD("Alexandroupoli Airport (Dimokritos Airport)","Alexandroupoli"),
    AHO("Alghero-Fertilia Airport","Alghero"),
    ALC("Alicante–Elche Airport","Alicante"),
    LEI("Almería Airport","Almería"),
    AHZ("Alpe d'Huez Airport","Alpe d'Huez"),
    ALF("Alta Airport","Alta"),
    AOC("Leipzig–Altenburg Airport","Altenburg"),
    ACH("St. Gallen–Altenrhein Airport","Altenrhein"),
    AMS("Amsterdam Airport Schiphol","Amsterdam"),
    AOI("Ancona Falconara Airport","Ancona"),
    ANX("Andøya Airport, Andenes","Andenes"),
    AGH("Ängelholm–Helsingborg Airport (former ICAO: ESDB)","Ängelholm"),
    ANE("Angers – Loire Airport","Angers"),
    VLY("Anglesey Airport / RAF Valley","Anglesey"),
    ANG("Angoulême – Cognac International Airport","Angoulême"),
    NCY("Annecy – Haute-Savoie – Mont Blanc Airport","Annecy"),
    ANR("Antwerp International Airport","Antwerp"),
    AOT("Aosta Valley Airport","Aosta"),
    ARW("Arad International Airport","Arad"),
    AJR("Arvidsjaur Airport","Arvidsjaur"),
    JTY("Astypalaia Island National Airport","Astypalaia"),
    ATH("Athens International Airport (Eleftherios Venizelos Airport)","Athens"),
    OBS("Aubenas Aerodrome[1] (Ardèche Méridionale Aerodrome)","Aubenas"),
    AGB("Augsburg Airport","Augsburg"),
    AUR("Aurillac – Tronquières Airport","Aurillac"),
    AUF("Auxerre – Branches Aerodrome","Auxerre"),
    AVB("Aviano Air Base","Aviano"),
    AVN("Avignon – Provence Airport","Avignon"),
    BCM("Bacău International Airport","Bacău"),
    BJZ("Badajoz Airport (Talavera la Real Air Base)","Badajoz"),
    BAY("Baia Mare Airport","Baia Mare"),
    BOL("Ballykelly Airfield (RAF Ballykelly)","Ballykelly"),
    BMR("Baltrum Airport","Baltrum"),
    BYT("Bantry Aerodrome","Bantry"),
    BCN("Barcelona–El Prat Airport","Barcelona"),
    BAE("Barcelonnette – Saint-Pons Airport","Barcelonnette"),
    BDU("Bardufoss Airport","Bardufoss"),
    BRI("Bari Karol Wojtyła Airport","Bari"),
    BRR("Barra Airport","Barra"),
    BWF("Barrow/Walney Island Airport","Barrow-in-Furness"),
    BSL("EuroAirport Basel-Mulhouse-Freiburg","Basel"),
    BIA("Bastia – Poretta Airport","Bastia"),
    BJF("Båtsfjord Airport","Båtsfjord"),
    BYU("Bindlacher Berg Airport","Bayreuth"),
    BVA("Beauvais–Tillé Airport","Beauvais"),
    BYJ("Beja Airport","Beja"),
    BFS("Belfast International Airport","Belfast"),
    BLX("Belluno Airport","Belluno"),
    BLY("Belmullet Aerodrome","Belmullet"),
    BBP("Bembridge Airport","Bembridge"),
    BEB("Benbecula Airport","Benbecula"),
    BEX("RAF Benson","Benson"),
    BGO("Bergen Airport, Flesland","Bergen"),
    WOE("Woensdrecht Air Base","Bergen op Zoom"),
    EGC("Bergerac Dordogne Périgord Airport","Bergerac"),
    BVG("Berlevåg Airport","Berlevåg"),
    TXL("Berlin Tegel Airport","Berlin"),
    BRN("Bern Airport","Bern"),
    BZR("Béziers Cap d'Agde Airport","Béziers"),
    BXP("Biała Podlaska Airport","Biała Podlaska"),
    BIQ("Biarritz Pays Basque Airport","Biarritz"),
    BFE("Bielefeld Airport","Bielefeld"),
    BIO("Bilbao Airport","Bilbao"),
    BLL("Billund Airport","Billund"),
    BHX("Birmingham Airport","Birmingham"),
    BBJ("Bitburg Airport (former Bitburg Air Base)","Bitburg"),
    BLK("Blackpool Airport","Blackpool"),
    BOO("Bodø Airport","Bodø"),
    BWK("Bol Airport (Brač Airport)","Bol"),
    BLQ("Bologna Guglielmo Marconi Airport","Bologna"),
    BZO("Bolzano Airport","Bolzano"),
    BOD("Bordeaux–Mérignac Airport","Bordeaux"),
    BMK("Borkum Airfield","Borkum"),
    BLE("Dala Airport (Borlänge Airport)","Borlänge"),
    QXB("Aix les Milles, France","Bouches-du-Rhône"),
    BOU("Bourges Airport","Bourges"),
    BOH("Bournemouth Airport","Bournemouth"),
    BGZ("Braga Airport","Braga"),
    BGC("Bragança Airport","Bragança"),
    LKZ("RAF Lakenheath","Brandon"),
    BTS("M. R. Štefánik Airport","Bratislava"),
    BWE("Braunschweig–Wolfsburg Airport","Braunschweig"),
    GLZ("Gilze-Rijen Air Base","Breda"),
    BRE("Bremen Airport","Bremen"),
    BRV("Bremerhaven Airport","Bremerhaven"),
    VBS("Brescia Airport (Gabriele D'Annunzio Airport)","Brescia"),
    BES("Brest Bretagne Airport","Brest"),
    BDS("Brindisi – Salento Airport","Brindisi"),
    BRS("Bristol Airport","Bristol"),
    BVE("Brive–Souillac Airport","Brive-la-Gaillarde"),
    BRQ("Brno–Tuřany Airport","Brno"),
    BNN("Brønnøysund Airport, Brønnøy","Brønnøysund"),
    BRU("Brussels Airport (Zaventem Airport)","Brussels"),
    OTP("Henri Coandă International Airport","Bucharest"),
    BUD("Budapest Ferenc Liszt International Airport","Budapest"),
    BXO("Buochs Airport","Buochs"),
    URD("Burg Feuerstein Airport[1]","Burg Feuerstein"),
    BOJ("Burgas Airport","Burgas"),
    RGS("Burgos Airport","Burgos"),
    BEQ("RAF Honington","Bury St Edmunds"),
    BZG("Bydgoszcz Ignacy Jan Paderewski Airport","Bydgoszcz"),
    CFR("Caen – Carpiquet Airport","Caen"),
    CAG("Cagliari Elmas Airport","Cagliari"),
    ZAO("Cahors - Lalbenque Airport","Cahors"),
    CQF("Calais–Dunkerque Airport","Calais / Dunkirk"),
    CLY("Calvi – Sainte-Catherine Airport","Calvi"),
    CBG("Cambridge Airport","Cambridge"),
    CAL("Campbeltown Airport / RAF Machrihanish","Campbeltown"),
    CEQ("Cannes – Mandelieu Airport","Cannes"),
    CSB("Caransebeș Airport","Caransebeș"),
    CCF("Carcassonne Airport","Carcassonne"),
    CWL("Cardiff Airport","Cardiff"),
    CAX("Carlisle Lake District Airport","Carlisle"),
    BZZ("RAF Brize Norton","Carterton"),
    CAT("Cascais Municipal Aerodrome[1]","Cascais"),
    CDT("Castellón–Costa Azahar Airport","Castellón de la Plana"),
    DCM("Castres–Mazamet Airport","Castres"),
    CTA("Catania–Fontanarossa Airport","Catania"),
    EFL("Cephalonia International Airport","Cephalonia"),
    XCR("Châlons Vatry Airport","Châlons-en-Champagne"),
    CMF("Chambéry-Savoie Airport","Chambéry"),
    CHQ("Chania International Airport (Ioannis Daskalogiannis)","Chania"),
    CRL("Brussels South Charleroi Airport","Charleroi"),
    CHR("Châteauroux-Centre Marcel Dassault Airport","Châteauroux"),
    CHV("Chaves Airport","Chaves"),
    CER("Cherbourg – Maupertus Airport","Cherbourg-Octeville"),
    CEG("Hawarden Airport (Chester Airport)","Chester"),
    QUG("Chichester/Goodwood Airport","Chichester"),
    JKH("Chios Island National Airport","Chios"),
    CET("Cholet Le Pontreau Airport","Cholet"),
    CQM("Ciudad Real Central Airport","Ciudad Real"),
    CFE("Clermont-Ferrand Auvergne Airport","Clermont-Ferrand"),
    VAC("Varrelbusch Airport[1]","Cloppenburg"),
    CLJ("Cluj-Napoca International Airport","Cluj-Napoca"),
    CNG("Cognac – Châteaubernard Air Base","Cognac"),
    CBP("Coimbra Airport","Coimbra"),
    COL("Coll Airport","Coll"),
    CMR("Colmar – Houssen Airport","Colmar"),
    CGN("Cologne Bonn Airport","Cologne / Bonn"),
    CSA("Colonsay Airport","Colonsay"),
    CIY("Comiso Airport","Comiso"),
    QCY("RAF Coningsby","Coningsby"),
    CND("Mihail Kogălniceanu International Airport","Constanța"),
    CPH("Copenhagen Airport, Kastrup","Copenhagen"),
    ODB("Córdoba Airport","Córdoba"),
    CFU("Corfu International Airport (Ioannis Kapodistrias Int'l Airport)","Corfu"),
    ORK("Cork Airport","Cork"),
    CVU("Corvo Airport","Corvo Island"),
    CBU("Cottbus-Drewitz Airport","Cottbus"),
    CVF("Courchevel Altiport","Courchevel"),
    CVT("Coventry Airport","Coventry"),
    CRA("Craiova International Airport","Craiova"),
    CSF("Creil Air Base","Creil"),
    CRV("Crotone Airport (Sant'Anna Airport)","Crotone"),
    CUF("Cuneo International Airport","Cuneo"),
    FCN("Nordholz Naval Airbase","Cuxhaven"),
    CZW("Częstochowa-Rudniki Airport","Częstochowa"),
    DGP("Daugavpils International Airport","Daugavpils"),
    DOL("Deauville – Saint-Gatien Airport","Deauville"),
    DEB("Debrecen International Airport","Debrecen"),
    DCI("Decimomannu Air Base","Decimomannu"),
    DHR("De Kooy Airfield","Den Helder"),
    LDY("City of Derry Airport","Derry (Londonderry)"),
    DPE("Dieppe - Saint-Aubin Airport","Dieppe"),
    DIJ("Dijon Air Base","Dijon"),
    DNR("Dinard–Pleurtuit–Saint-Malo Airport","Dinard / Saint-Malo"),
    DLE("Dole–Jura Airport","Dole"),
    ZBE("Zábřeh Airport","Dolní Benešov"),
    DSA("Robin Hood Airport Doncaster Sheffield","Doncaster"),
    CFN("Donegal Airport","Donegal"),
    HOH("Hohenems-Dornbirn Airport","Dornbirn"),
    DOC("Dornoch Airport","Dornoch"),
    DTM("Dortmund Airport","Dortmund"),
    DRS("Dresden Airport","Dresden"),
    DUB("Dublin Airport","Dublin"),
    DBV("Dubrovnik Airport","Dubrovnik"),
    DND("Dundee Airport","Dundee"),
    DUS("Düsseldorf Airport","Düsseldorf"),
    EOI("Eday Airport","Eday"),
    EDI("Edinburgh Airport","Edinburgh"),
    EIN("Eindhoven Airport","Eindhoven"),
    EIB("Eisenach-Kindel Airport[1]","Eisenach"),
    EBA("Marina di Campo Airport","Elba Island"),
    EME("Emden Airport","Emden"),
    EML("Emmen Air Base","Emmen"),
    ENK("Enniskillen/St Angelo Airport","Enniskillen"),
    ENF("Enontekiö Airport","Enontekiö"),
    ENS("Enschede Airport Twente","Enschede"),
    EPL("Épinal – Mirecourt Airport","Épinal / Mirecourt"),
    ERF("Erfurt–Weimar Airport","Erfurt"),
    EBJ("Esbjerg Airport","Esbjerg"),
    EKT("Eskilstuna Airport","Eskilstuna"),
    ESS("Essen/Mülheim Airport","Essen"),
    EVX("Évreux-Fauville Air Base","Évreux"),
    EXT("Exeter International Airport","Exeter"),
    VDB("Fagernes Airport, Leirin","Fagernes"),
    FIE("Fair Isle Airport","Fair Isle"),
    FFD("RAF Fairford","Fairford"),
    FAB("Farnborough Airport","Farnborough"),
    FAO("Faro Airport","Faro"),
    FEA("Fetlar Airport","Fetlar"),
    FSC("Figari–Sud Corse Airport","Figari"),
    FLF("Flensburg-Schäferhaus Airport","Flensburg"),
    FLR("Florence Airport, Peretola (Amerigo Vespucci Airport)","Florence"),
    FLW("Flores Airport","Flores Island"),
    FRO("Florø Airport","Florø"),
    FLH("Flotta Island Airport","Flotta"),
    FOG("Foggia Gino Lisa Airport","Foggia"),
    FDE("Førde Airport, Bringeland","Førde"),
    FRL("Forlì International Airport (Luigi Ridolfi Airport)","Forlì"),
    FSS("RAF Kinloss","Forres"),
    FOA("Foula Airfield","Foula"),
    FRA("Frankfurt Airport","Frankfurt"),
    FDH("Friedrichshafen Airport (Bodensee Airport)","Friedrichshafen"),
    FRZ("Fritzlar Air Base","Fritzlar"),
    FUE("Fuerteventura Airport","Fuerteventura"),
    FNC("Madeira Airport","Funchal"),
    FEL("Fürstenfeldbruck Air Base","Fürstenfeldbruck"),
    GEV("Gällivare Airport","Gällivare"),
    GWY("Galway Airport","Galway"),
    GAT("Gap–Tallard Airport","Gap"),
    GVX("Gävle-Sandviken Airport","Gävle"),
    GDN("Gdańsk Lech Wałęsa Airport","Gdańsk"),
    GEC("Geçitkale Air Base","Geçitkale"),
    GKE("NATO Air Base Geilenkirchen","Geilenkirchen"),
    GVA("Geneva Airport","Geneva"),
    GOA("Genoa Cristoforo Colombo Airport","Genoa"),
    GHF("Giebelstadt Airport","Giebelstadt"),
    GRO("Girona–Costa Brava Airport","Girona"),
    PIK("Glasgow Prestwick Airport","Glasgow"),
    GLO("Gloucestershire Airport","Gloucester / Cheltenham"),
    GLL("Gol Airport, Klanten","Gol"),
    GOZ("Gorna Oryahovitsa Airport","Gorna Oryahovitsa"),
    GOT("Göteborg Landvetter Airport","Gothenburg"),
    GRW("Graciosa Airport","Graciosa"),
    LPA("Gran Canaria Airport","Gran Canaria"),
    GRX("Federico García Lorca Airport (Granada Jaén Airport)","Granada"),
    GFR("Granville–Mont-Saint-Michel Aerodrome [fr]","Granville"),
    GRZ("Graz Airport","Graz"),
    LHB("Bruntingthorpe Aerodrome (Leicester Harboro'/Harbour Airport)","Greater Leicester"),
    GNB("Grenoble–Isère Airport","Grenoble"),
    GRQ("Groningen Airport Eelde","Groningen"),
    GRS("Grosseto Airport","Grosseto"),
    GCI("Guernsey Airport","Guernsey"),
    GUT("RAF Gütersloh","Gütersloh"),
    GTI("Rügen Airport (Güttin Airfield)","Güttin"),
    HFS("Hagfors Airport","Hagfors"),
    HHN("Frankfurt–Hahn Airport","Hahn"),
    HAD("Halmstad Airport (Halmstad City Airport)","Halmstad"),
    HMR("Hamar Airport, Stafsberg","Hamar"),
    HAM("Hamburg Airport","Hamburg"),
    HFT("Hammerfest Airport","Hammerfest"),
    HAJ("Hannover Airport","Hanover"),
    EVE("Harstad/Narvik Airport, Evenes","Harstad / Narvik"),
    HKV("Haskovo Malevo Airport","Haskovo"),
    HAA("Hasvik Airport","Hasvik"),
    HAU("Haugesund Airport, Karmøy","Haugesund"),
    HAW("Haverfordwest Aerodrome","Haverfordwest"),
    HZB("Merville–Calonne Airport","Hazebrouck"),
    HEI("Heide–Büsum Airport","Heide / Büsum"),
    HDB("Heidelberg Airport","Heidelberg"),
    HGL("Heligoland Airport (Düne Airport)","Heligoland"),
    HEL("Helsinki Airport (Helsinki-Vantaa Airport)","Helsinki"),
    HMV("Hemavan Tärnaby Airport","Hemavan / Tärnaby"),
    HER("Heraklion International Airport (Nikos Kazantzakis Airport)","Heraklion"),
    HDF("Heringsdorf Airport","Heringsdorf"),
    SOB("Hévíz–Balaton Airport","Hévíz"),
    HYC("Wycombe Air Park","High Wycombe"),
    HOQ("Hof–Plauen Airport","Hof"),
    HVG("Honningsvåg Airport, Valan","Honningsvåg"),
    HOR("Horta Airport","Horta"),
    HUV("Hudiksvall Airport","Hudiksvall"),
    HSK("Huesca–Pirineos Airport","Huesca"),
    HLF("Hultsfred-Vimmerby Airport","Hultsfred / Vimmerby"),
    QHU("Husum Schwesing Airport[1]","Husum"),
    HYV("Hyvinkää Airfield","Hyvinkää"),
    IAS("Iași International Airport","Iași"),
    IBZ("Ibiza Airport","Ibiza"),
    IDB("Idre Airport","Idre"),
    JIK("Ikaria Island National Airport","Ikaria Island"),
    IDY("Île d'Yeu Aerodrome","Île d'Yeu"),
    ILH("Illesheim Army Airfield","Illesheim"),
    IGS("Ingolstadt Manching Airport","Ingolstadt"),
    INQ("Inisheer Aerodrome","Inisheer"),
    IIA("Inishmaan Aerodrome","Inishmaan"),
    IOR("Inishmore Aerodrome (Kilronan Airport)","Inishmore"),
    INN("Innsbruck Airport (Kranebitten Airport)","Innsbruck"),
    INV("Inverness Airport","Inverness"),
    IOA("Ioannina National Airport","Ioannina"),
    ILY("Islay Airport (Glenegedale Airport)","Islay"),
    IOM("Isle of Man Airport (Ronaldsway Airport)","Isle of Man"),
    SKL("Broadford Airfield[1]","Isle of Skye"),
    IVL("Ivalo Airport","Ivalo"),
    XRY("Jerez Airport (La Parra Airport)","Jerez de la Frontera"),
    JER("Jersey Airport","Jersey"),
    JOE("Joensuu Airport","Joensuu"),
    JKG("Jönköping Airport","Jönköping"),
    JUI("Juist Airport","Juist"),
    JYV("Jyväskylä Airport","Jyväskylä"),
    KAJ("Kajaani Airport","Kajaani"),
    KLX("Kalamata International Airport","Kalamata"),
    KLR("Kalmar Airport","Kalmar"),
    JKL("Kalymnos Island National Airport","Kalymnos"),
    KDL("Kärdla Airport","Kärdla"),
    KLV("Karlovy Vary Airport","Karlovy Vary"),
    KSK("Karlskoga Airport","Karlskoga"),
    FKB("Karlsruhe/Baden-Baden Airport","Karlsruhe / Baden-Baden"),
    KSD("Karlstad Airport","Karlstad"),
    AOK("Karpathos Island National Airport","Karpathos"),
    KRP("Karup Airport","Karup"),
    KSJ("Kasos Island Public Airport","Kasos Island"),
    KSF("Kassel Airport","Kassel"),
    KZS("Kastellorizo Island Public Airport","Kastellorizo"),
    KSO("Kastoria National Airport (Aristotelis Airport)","Kastoria"),
    KTW("Katowice International Airport","Katowice"),
    KHJ("Kauhajoki Airfield","Kauhajoki"),
    KAU("Kauhava Airfield","Kauhava"),
    KUN("Kaunas International Airport","Kaunas"),
    KVA("Kavala International Airport (Alexander the Great Airport)","Kavala"),
    GBA("Cotswold Airport[2]","Kemble"),
    KEM("Kemi-Tornio Airport","Kemi / Tornio"),
    KIR("Kerry Airport (Farranfore Airport)","Kerry"),
    KEL("Kiel Airport","Kiel"),
    KKY("Kilkenny Airport","Kilkenny"),
    KNF("RAF Marham","King's Lynn"),
    HUY("Humberside Airport","Kingston upon Hull"),
    KKN("Kirkenes Airport, Høybuktmoen","Kirkenes"),
    KOI("Kirkwall Airport","Kirkwall"),
    KRN("Kiruna Airport","Kiruna"),
    KTQ("Kitee Airfield","Kitee"),
    KTT("Kittilä Airport","Kittilä"),
    KZG("Kitzingen Airport","Kitzingen"),
    KLU("Klagenfurt Airport","Klagenfurt"),
    NOC("Ireland West Airport Knock","Knock"),
    KOK("Kokkola-Pietarsaari Airport","Kokkola / Jakobstad"),
    KJK("Kortrijk–Wevelgem International Airport","Kortrijk"),
    KGS("Kos Island International Airport","Kos"),
    KSC("Košice International Airport","Košice"),
    OSZ("Koszalin-Zegrze Pomorskie Airport[1]","Koszalin"),
    KOQ("Köthen Airport","Köthen"),
    KZI("Kozani National Airport (Filippos Airport)","Kozani"),
    KRK("John Paul II International Airport Kraków–Balice","Kraków"),
    KRF("Höga Kusten Airport (Kramfors-Sollefteå Airport)","Kramfors / Sollefteå"),
    KRS("Kristiansand Airport, Kjevik","Kristiansand"),
    KID("Kristianstad Airport","Kristianstad"),
    KSU("Kristiansund Airport, Kvernberget","Kristiansund"),
    KUO("Kuopio Airport","Kuopio"),
    KEV("Halli Airport","Kuorevesi"),
    URE("Kuressaare Airport","Kuressaare"),
    KAO("Kuusamo Airport","Kuusamo"),
    KIT("Kithira Island National Airport","Kythira"),
    QAQ("L'Aquila–Preturo Airport[1]","L'Aquila"),
    LBY("La Baule-Escoublac Airport","La Baule-Escoublac"),
    GMZ("La Gomera Airport","La Gomera / Canary Islands"),
    SPC("La Palma Airport","La Palma"),
    EDM("La Roche-sur-Yon Aerodrome","La Roche-sur-Yon"),
    LRH("La Rochelle – Île de Ré Airport","La Rochelle"),
    LEU("La Seu d'Urgell Airport","La Seu d'Urgell"),
    BYR("Læsø Airport","Læsø"),
    LHA("Flughafen Lahr (Lahr Airport)","Lahr"),
    LKL("Lakselv Airport, Banak","Lakselv"),
    SUF("Lamezia Terme International Airport","Lamezia Terme"),
    LMP("Lampedusa Airport","Lampedusa"),
    LDV("Landivisiau Air Base","Landivisiau"),
    LGO("Langeoog Airport","Langeoog"),
    LAI("Lannion – Côte de Granit Airport","Lannion"),
    ACE("Lanzarote Airport","Lanzarote"),
    LPP("Lappeenranta Airport","Lappeenranta"),
    LRA("Larissa National Airport","Larissa"),
    LCA("Larnaca International Airport","Larnaca"),
    LVA("Laval Entrammes Airport","Laval"),
    CTT("Le Castellet Airport","Le Castellet"),
    LEH("Le Havre – Octeville Airport","Le Havre"),
    LME("Le Mans Arnage Airport","Le Mans"),
    LPY("Le Puy – Loudes Airport","Le Puy-en-Velay"),
    LTQ("Le Touquet – Côte d'Opale Airport","Le Touquet-Paris-Plage"),
    LCC("Galatina Air Base","Lecce"),
    LBA("Leeds Bradford Airport","Leeds / Bradford"),
    LWR("Leeuwarden Air Base","Leeuwarden"),
    LRC("Leicester City Airport","Leicester"),
    LEJ("Leipzig/Halle Airport","Leipzig"),
    LKN("Leknes Airport","Leknes"),
    LEY("Lelystad Airport","Lelystad"),
    LXS("Lemnos International Airport","Lemnos (Limnos)"),
    XLW("Lemwerder Airport","Lemwerder"),
    LEN("León Airport","León"),
    LRS("Leros Municipal Airport","Leros"),
    LWK("Tingwall Airport (Lerwick/Tingwall Airport)","Lerwick"),
    LSO("Les Sables-d'Olonne – Talmont Airport","Les Sables-d'Olonne"),
    LTR("Letterkenny Airfield","Letterkenny"),
    LDK("Lidköping-Hovby Airport","Lidköping"),
    LGG("Liège Airport","Liège"),
    LPX("Liepāja International Airport","Liepāja"),
    LIL("Lille Airport (Lille–Lesquin Airport)","Lille"),
    LIG("Limoges – Bellegarde Airport","Limoges"),
    LPI("Linköping/Saab Airport","Linköping"),
    HRT("RAF Linton-on-Ouse","Linton-on-Ouse"),
    LNZ("Linz Airport (Blue Danube Airport)","Linz"),
    LIS("Lisbon Portela Airport","Lisbon"),
    LPL("Liverpool John Lennon Airport","Liverpool"),
    LJU("Ljubljana Jože Pučnik Airport (Brnik Airport)","Ljubljana"),
    ILD("Lleida–Alguaire Airport","Lleida"),
    LCJ("Łódź Władysław Reymont Airport","Łódź"),
    RJL("Logroño–Agoncillo Airport","Logroño"),
    LHR("Heathrow Airport","London"),
    BQH("London Biggin Hill Airport","London / Biggin Hill"),
    SEN("London Southend Airport","London / Southend"),
    HOY("Hoy Island Airport","Longhope"),
    LYR("Svalbard Airport, Longyear","Longyearbyen"),
    LRT("Lorient South Brittany Airport (Lann-Bihoué Airport)","Lorient"),
    LSZ("Lošinj Airport","Lošinj"),
    LMO("RAF Lossiemouth","Lossiemouth"),
    LBC("Lübeck Airport","Lübeck"),
    LUZ("Lublin Airport","Lublin"),
    LCV("Lucca-Tassignano Airport","Lucca"),
    LUE("Boľkovce Airport","Lučenec"),
    LUG("Lugano Airport","Lugano"),
    LLA("Luleå Airport (Kallax Airport)","Luleå"),
    MLA("Malta International Airport (Luqa Airport)","Luqa"),
    LUX("Luxembourg Findel Airport","Luxembourg"),
    LYC("Lycksele Airport","Lycksele"),
    LYX("Lydd Airport (London Ashford Airport)","Lydd"),
    LYE("RAF Lyneham","Lyneham"),
    LYS("Lyon–Saint-Exupéry Airport","Lyon"),
    MST("Maastricht Aachen Airport","Maastricht"),
    MAD("Adolfo Suárez Madrid–Barajas Airport","Madrid"),
    CSO("Magdeburg–Cochstedt Airport","Magdeburg"),
    AGP("Málaga Airport","Málaga"),
    MMX("Malmö Airport","Malmö"),
    MAN("Manchester Airport","Manchester"),
    MHG("Mannheim City Airport","Mannheim"),
    MSE("Manston Airport (Kent International Airport)","Manston"),
    MKA("Mariánské Lázně Airport","Mariánské Lázně"),
    MRW("Lolland Falster Airport","Maribo"),
    MBX("Maribor Edvard Rusjan Airport","Maribor"),
    MHQ("Mariehamn Airport","Mariehamn"),
    MRS("Marseille Provence Airport","Marseille"),
    MVV("Megève Altiport","Megève"),
    MEH("Mehamn Airport","Mehamn"),
    MLN("Melilla Airport","Melilla"),
    FMM("Memmingen Airport","Memmingen"),
    MEN("Brenoux Airport","Mende"),
    MAH("Menorca Airport (Mahón Airport)","Menorca"),
    MFX("Méribel Altiport","Méribel"),
    MZM("Metz-Frescaty Air Base","Metz"),
    ETZ("Metz–Nancy–Lorraine Airport","Metz / Nancy"),
    MIK("Mikkeli Airport","Mikkeli"),
    MXP("Milan–Malpensa Airport","Milan"),
    BGY("Il Caravaggio International Airport (Orio al Serio Airport)","Milan / Bergamo"),
    MHZ("RAF Mildenhall","Mildenhall"),
    MLO("Milos Island National Airport","Milos"),
    MCQ("Miskolc Airport","Miskolc"),
    MQN("Mo i Rana Airport, Røssvoll","Mo i Rana"),
    MOL("Molde Airport, Årø","Molde"),
    MGL("Düsseldorf Mönchengladbach Airport","Mönchengladbach"),
    SCP("Mont-Dauphin - Saint-Crépin Airport[1]","Mont-Dauphin"),
    MCU("Montluçon – Guéret Airport","Montluçon"),
    MPL("Montpellier–Méditerranée Airport (Fréjorgues Airport)","Montpellier"),
    MXX("Mora–Siljan Airport","Mora"),
    MXN("Morlaix – Ploujean Airport","Morlaix"),
    OZP("Morón Air Base[1]","Morón de la Frontera"),
    MJF("Mosjøen Airport, Kjærstad","Mosjøen"),
    MLH("EuroAirport Basel Mulhouse Freiburg","Mulhouse"),
    ULL("Glenforsa Airfield[1]","Mull"),
    MUC("Munich Airport","Munich"),
    FMO("Münster Osnabrück International Airport","Münster / Osnabrück (LS)"),
    MJV("Murcia–San Javier Airport","Murcia"),
    RMU("Región de Murcia International Airport[1]","Murcia / Cartagena"),
    JMK("Mykonos Island National Airport","Mykonos"),
    MJT("Mytilene International Airport","Mytilene"),
    OSY("Namsos Airport, Høknesøra","Namsos"),
    ENC("Nancy-Essey Airport","Nancy"),
    NTE("Nantes Atlantique Airport","Nantes"),
    NAP("Naples International Airport","Naples"),
    NVK("Narvik Airport, Framnes","Narvik"),
    JNX("Naxos Island National Airport","Naxos"),
    FNB("Neubrandenburg Airport","Neubrandenburg"),
    EUM("Neumünster Airport","Neumünster"),
    NVS("Nevers - Fourchambault Airport[1]","Nevers"),
    NCL("Newcastle Airport","Newcastle upon Tyne"),
    NQY("Newquay Airport","Newquay"),
    NCE("Nice Côte d'Azur Airport","Nice"),
    NIC("Nicosia International Airport1","Nicosia"),
    ECN("Ercan International Airport[1]","Nicosia (Lefkoşa)"),
    FNI("Nîmes–Alès–Camargue–Cévennes Airport (Garons Airport)","Nîmes"),
    NIT("Niort - Souché Airport[1]","Niort"),
    NOD("Norddeich Airport","Norden"),
    NRD("Norderney Airport","Norderney"),
    NRK("Norrköping Airport","Norrköping"),
    NRL("North Ronaldsay Airport[1]","North Ronaldsay"),
    ORM("Sywell Aerodrome","Northampton"),
    NHT("RAF Northolt","Northolt"),
    NWI("Norwich International Airport","Norwich"),
    NTB("Notodden Airport, Tuven","Notodden"),
    NQT("Nottingham Airport[1]","Nottingham"),
    EMA("East Midlands Airport","Nottingham / Leicester / Derby"),
    NUE("Nuremberg Airport","Nuremberg"),
    OKH("RAF Cottesmore","Oakham"),
    OBN("Oban Airport[1] (North Connel Airport)","Oban"),
    OBF("Oberpfaffenhofen Airport","Oberpfaffenhofen"),
    ODE("Hans Christian Andersen Airport","Odense"),
    ODH("RAF Odiham","Odiham"),
    OLB("Olbia Costa Smeralda Airport","Olbia"),
    OLO("Olomouc Airport (Neředín Airport)","Olomouc"),
    ZHZ("Halle-Oppin Airport","Oppin"),
    OMR("Oradea International Airport","Oradea"),
    ORB("Örebro Airport","Örebro"),
    FNU("Oristano-Fenosu Airport[1]","Oristano"),
    OLA("Ørland Airport[1]","Ørland"),
    ORE("Orléans – Saint-Denis-de-l'Hôtel Airport[1]","Orléans"),
    OER("Örnsköldsvik Airport","Örnsköldsvik"),
    HOV("Ørsta–Volda Airport, Hovden","Ørsta / Volda"),
    OSI("Osijek Airport","Osijek"),
    OSK("Oskarshamn Airport","Oskarshamn"),
    OSL("Oslo Airport, Gardermoen","Oslo"),
    RYG("Moss Airport, Rygge / Rygge Air Station","Oslo / Moss"),
    OST("Ostend–Bruges International Airport","Ostend / Bruges"),
    OSD("Åre Östersund Airport","Östersund"),
    OSR("Leoš Janáček Airport Ostrava","Ostrava"),
    OUL("Oulu Airport","Oulu"),
    OUK("Out Skerries Airport[1]","Out Skerries"),
    OVD("Asturias Airport (Oviedo Airport)","Oviedo"),
    OXF("Oxford Airport (London Oxford Airport)","Oxford"),
    PAD("Paderborn Lippstadt Airport","Paderborn / Lippstadt"),
    PJA("Pajala Airport","Pajala"),
    PLQ("Palanga International Airport","Palanga"),
    PMO("Falcone–Borsellino Airport (Punta Raisi Airport)","Palermo"),
    PMI("Palma de Mallorca Airport","Palma de Mallorca"),
    PNA("Pamplona Airport","Pamplona"),
    PNV("Panevėžys Air Base[1] (Pajuostis Airport)","Panevėžys"),
    PNL("Pantelleria Airport[1]","Pantelleria"),
    PSV("Papa Stour Airport[1]","Papa Stour"),
    PPW("Papa Westray Airport","Papa Westray"),
    PFO("Paphos International Airport","Paphos"),
    PED("Pardubice Airport","Pardubice"),
    CDG("Charles de Gaulle Airport (Roissy Airport)","Paris"),
    PMF("Parma Airport (Giuseppe Verdi Airport)","Parma"),
    EPU("Pärnu Airport","Pärnu"),
    PAS("Paros National Airport","Paros"),
    GPA("Araxos Airport","Patras"),
    PUF("Pau Pyrénées Airport","Pau"),
    PEV("Pécs-Pogány International Airport[1]","Pécs"),
    PEF("Peenemünde Airfield[1]","Peenemünde"),
    PGX("Périgueux Bassillac Airport","Périgueux"),
    PGF("Perpignan–Rivesaltes Airport","Perpignan"),
    PSL("Perth Airport (Scone Airport)","Perth"),
    PEG("Perugia San Francesco d'Assisi – Umbria International Airport","Perugia"),
    PSR("Abruzzo Airport","Pescara"),
    PIX("Pico Airport","Pico Island"),
    PZY("Piešťany Airport","Piešťany"),
    PSA("Pisa International Airport (Galileo Galilei Airport)","Pisa"),
    PDV("Plovdiv Airport","Plovdiv"),
    PLH("Plymouth City Airport","Plymouth"),
    PIS("Poitiers–Biard Airport","Poitiers"),
    PDL("João Paulo II Airport","Ponta Delgada"),
    TAT("Poprad–Tatry Airport","Poprad"),
    POR("Pori Airport","Pori"),
    PRM("Portimão Airport","Portimão"),
    OPO("Francisco de Sá Carneiro Airport","Porto"),
    PKH("Porto Cheli Airport","Porto Cheli (Portochelion)"),
    PXO("Porto Santo Airport","Porto Santo Island"),
    POW("Portorož Airport","Portorož"),
    POZ("Poznań–Ławica Airport","Poznań"),
    PRG("Václav Havel Airport Prague","Prague"),
    PRV("Přerov Airport[1]","Přerov"),
    POV("Prešov Air Base[1]","Prešov"),
    PVK("Aktion National Airport","Preveza / Lefkada"),
    PRP("Propriano Airport","Propriano"),
    PUY("Pula Airport","Pula"),
    PYR("Andravida Air Base[1]","Pyrgos"),
    UIP("Quimper–Cornouaille Airport (Pluguffan)","Quimper"),
    RDO("Radom Airport[1]","Radom"),
    RMS("Ramstein Air Base","Ramstein"),
    RAN("Ravenna Airport[1]","Ravenna"),
    REB("Rechlin–Lärz Airfield[1]","Rechlin"),
    REG("Reggio di Calabria Airport","Reggio di Calabria"),
    RHE("Reims – Champagne Air Base","Reims"),
    RNS("Rennes–Saint-Jacques Airport","Rennes"),
    REU("Reus Airport","Reus"),
    RHO("Rhodes International Airport","Rhodes"),
    IES("Riesa–Göhlis Airfield","Riesa"),
    RIX("Riga International Airport","Riga"),
    RJK("Rijeka Airport","Rijeka"),
    RMI("Federico Fellini International Airport","Rimini"),
    RNE("Roanne Renaison Airport","Roanne"),
    RCO("Rochefort – Saint-Agnant Airport[1]","Rochefort"),
    RCS("Rochester Airport","Rochester"),
    RDZ("Rodez–Marcillac Airport","Rodez"),
    FCO("Leonardo da Vinci–Fiumicino Airport","Rome"),
    RNN("Bornholm Airport","Rønne"),
    RNB("Ronneby Airport","Ronneby / Karlskrona"),
    RRS("Røros Airport","Røros"),
    RVK("Rørvik Airport, Ryum","Rørvik"),
    RET("Røst Airport","Røst"),
    RLG("Rostock–Laage Airport","Rostock"),
    ROZ("US Naval Station Rota[1]","Rota"),
    RTM("Rotterdam The Hague Airport","Rotterdam"),
    URO("Rouen Airport (Vallée de Seine Airport)","Rouen"),
    RVN("Rovaniemi Airport","Rovaniemi"),
    RYN("Royan – Médis Aerodrome","Royan"),
    ROU("Ruse Airport","Ruse"),
    RZE("Rzeszów–Jasionka Airport","Rzeszów"),
    SCN("Saarbrücken Airport","Saarbrücken"),
    SBK("Saint-Brieuc – Armor Airport","Saint-Brieuc"),
    EBU("Saint-Étienne–Bouthéon Airport","Saint-Étienne"),
    SNR("Saint-Nazaire Montoir Airport","Saint-Nazaire"),
    ZSE("Pierrefonds Airport","Saint-Pierre"),
    LTT("La Môle – Saint-Tropez Airport","Saint-Tropez"),
    SYT("Saint-Yan Airport[1] (Charolais Bourgogne Sud Airport)","Saint-Yan"),
    SLM("Salamanca Airport","Salamanca"),
    QSR("Salerno Costa d'Amalfi Airport (Pontecagnano Airport)","Salerno"),
    SZG("Salzburg Airport","Salzburg"),
    SMI("Samos International Airport Aristarchos of Samos","Samos"),
    EAS("San Sebastián Airport","San Sebastián"),
    SDN("Sandane Airport, Anda","Sandane"),
    NDY("Sanday Airport","Sanday"),
    TRF("Sandefjord Airport, Torp","Sandefjord / Oslo"),
    SSJ("Sandnessjøen Airport, Stokka","Sandnessjøen"),
    PSH("Sankt Peter-Ording Airport[1]","Sankt Peter-Ording"),
    SMA("Santa Maria Airport","Santa Maria Island"),
    SDR("Santander Airport","Santander"),
    SCQ("Santiago de Compostela Airport","Santiago de Compostela"),
    JTR("Santorini (Thira) National Airport","Santorini (Thira)"),
    SJZ("São Jorge Airport","São Jorge Island"),
    SOZ("Solenzara Air Base[1]","Sari-Solenzara"),
    SUJ("Satu Mare International Airport","Satu Mare"),
    SVL("Savonlinna Airport[1]","Savonlinna"),
    SQZ("RAF Scampton[1]","Scampton"),
    WBG("Schleswig Air Base","Schleswig"),
    SZW("Schwerin-Parchim International Airport","Schwerin"),
    SJY("Seinäjoki Airport","Seinäjoki"),
    SVQ("Seville Airport","Seville"),
    SNN("Shannon Airport","Shannon"),
    LSI("Sumburgh Airport","Shetland Islands"),
    ESH("Shoreham Airport (Brighton City Airport)","Shoreham-by-Sea"),
    SQQ("Šiauliai International Airport","Šiauliai"),
    SBZ("Sibiu International Airport","Sibiu"),
    SGE("Siegerland Airport","Siegen"),
    SAY("Siena–Ampugnano Airport","Siena"),
    SLS("Silistra Airfield","Silistra"),
    CNL("Sindal Airport","Sindal"),
    SIE("Sines Airport[1]","Sines"),
    SIR("Sion Airport","Sion"),
    JSH("Sitia Public Airport","Sitia"),
    SFT("Skellefteå Airport","Skellefteå"),
    JSI("Skiathos Island National Airport","Skiathos"),
    SKE("Skien Airport, Geiteryggen","Skien"),
    SQW("Skive Airport","Skive"),
    STA("Stauning Vestjylland Airport","Skjern"),
    KVB("Skövde Airport","Skövde"),
    SKU("Skyros Island National Airport","Skyros"),
    SLD("Sliač Airport","Sliač"),
    SXL("Sligo Airport","Sligo"),
    SOT("Sodankylä Airfield[1]","Sodankylä"),
    SOO("Söderhamn Airport[1] (Helsinge Airport)","Söderhamn"),
    SOF("Sofia Airport","Sofia"),
    SOG("Sogndal Airport, Haukåsen","Sogndal"),
    SGD("Sønderborg Airport","Sønderborg"),
    SOJ("Sørkjosen Airport","Sørkjosen"),
    SOU("Southampton Airport","Southampton"),
    SPM("Spangdahlem Air Base","Spangdahlem"),
    SPJ("Sparti Airport","Sparti (Sparta)"),
    NNR("Connemara Airport","Spiddal"),
    SPU("Split Airport","Split"),
    ADX("RAF Leuchars","St Andrews"),
    LEQ("Land's End Airport","St Just"),
    ISC("St Mary's Airport","St Mary's"),
    RUN("Roland Garros Airport","St-Denis"),
    SMV("Samedan Airport (Engadin Airport)","St. Moritz"),
    SZR("Stara Zagora Airport","Stara Zagora"),
    SVG("Stavanger Airport, Sola","Stavanger"),
    ARN("Stockholm Arlanda Airport","Stockholm"),
    NYO("Stockholm Skavsta Airport","Stockholm / Nyköping"),
    VST("Stockholm Västerås Airport","Stockholm / Västerås"),
    SKN("Stokmarknes Airport, Skagen","Stokmarknes"),
    SRP("Stord Airport, Sørstokken","Stord"),
    SYY("Stornoway Airport","Stornoway"),
    SQO("Storuman Airport[1]","Storuman"),
    BBH("Stralsund–Barth Airport","Stralsund / Barth"),
    SXB("Strasbourg Airport","Strasbourg"),
    RBM("Straubing Wallmühle Airport","Straubing"),
    SOY("Stronsay Airport","Stronsay"),
    STR("Stuttgart Airport","Stuttgart"),
    SCV("Suceava International Airport (Ștefan cel Mare Int'l)","Suceava"),
    SDL("Sundsvall-Timrå Airport (Midlanda Airport)","Sundsvall / Härnösand"),
    EVG("Sveg Airport","Sveg"),
    SVJ("Svolvær Airport, Helle","Svolvær"),
    SWS("Swansea Airport","Swansea"),
    GWT("Sylt Airport (Westerland Airport)","Sylt"),
    JSY("Syros Island National Airport","Syros"),
    SZZ("Solidarity Szczecin–Goleniów Airport","Szczecin"),
    SZY("Olsztyn-Mazury Regional Airport","Szczytno / Olsztyn"),
    TLL("Tallinn Airport (Lennart Meri Tallinn Airport)","Tallinn"),
    TMP("Tampere–Pirkkala Airport","Tampere"),
    TAR("Taranto-Grottaglie Airport","Taranto"),
    LDE("Tarbes–Lourdes–Pyrénées Airport","Tarbes / Lourdes"),
    TGV("Targovishte Airport[1] (Buhovtsi Airfield)","Targovishte"),
    TGM("Târgu Mureș International Airport","Târgu Mureș"),
    TAY("Tartu Airport","Tartu"),
    MME("Durham Tees Valley Airport","Teesside"),
    TFS("Tenerife–South Airport (Reina Sofia Airport)","Tenerife"),
    TER("Lajes Field","Terceira Island"),
    TEV("Teruel Airport[1]","Teruel"),
    SKG("Thessaloniki Airport Macedonia","Thessaloniki"),
    TED("Thisted Airport","Thisted"),
    TSR("Timișoara Traian Vuia International Airport","Timișoara"),
    TRE("Tiree Airport","Tiree"),
    TYF("Torsby Airport[1]","Torsby"),
    TTB("Tortolì Airport (Arbatax Airport)","Tortolì"),
    TLN("Toulon–Hyères Airport (Hyères Le Palyvestre Airport)","Toulon / Hyères"),
    TLS("Toulouse–Blagnac Airport","Toulouse"),
    TUF("Tours Val de Loire Airport","Tours"),
    TNF("Toussus-le-Noble Airport","Toussus-le-Noble"),
    TPS("Vincenzo Florio Airport Trapani–Birgi","Trapani"),
    TSF("Treviso-Sant'Angelo Airport","Treviso / Venice"),
    TRS("Trieste – Friuli Venezia Giulia Airport (Ronchi dei Legionari Airport)","Trieste"),
    THN("Trollhättan–Vänersborg Airport","Trollhättan / Vänersborg"),
    TOS("Tromsø Airport, Langnes","Tromsø"),
    TRD("Trondheim Airport, Værnes","Trondheim"),
    TCE("Tulcea Danube Delta Airport[1]","Tulcea"),
    TRN("Turin Airport (Caselle Airport)","Turin"),
    TKU("Turku Airport","Turku"),
    UDE("Volkel Air Base","Uden"),
    UDN("Campoformido Airport[1]","Udine"),
    UHE("Kunovice Airport","Uherské Hradiště"),
    UME("Umeå Airport","Umeå"),
    UNT("Unst Airport[1]","Unst"),
    UPV("RAF Upavon[1]","Upavon"),
    UTC("Soesterberg Air Base","Utrecht"),
    UTI("Utti Airport","Utti"),
    VAA("Vaasa Airport","Vaasa"),
    VDS("Vadsø Airport","Vadsø"),
    VAF("Valence-Chabeuil Airport","Valence"),
    VLC("Valencia Airport","Valencia"),
    VLL("Valladolid Airport","Valladolid"),
    VDE("El Hierro Airport[1]","Valverde"),
    VNE("Meucon Airport","Vannes"),
    VAW("Vardø Airport, Svartnes","Vardø"),
    VRK("Varkaus Airport","Varkaus"),
    VAR("Varna Airport","Varna"),
    VVK("Västervik Airport[1]","Västervik"),
    VXO("Växjö/Kronoberg Airport","Växjö"),
    VCE("Venice Marco Polo Airport","Venice"),
    VNT("Ventspils International Airport","Ventspils"),
    VRN("Verona Villafranca Airport","Verona"),
    VIC("Vicenza Airport","Vicenza"),
    VHY("Vichy — Charmeil Airport[1]","Vichy"),
    VIE("Vienna International Airport","Vienna"),
    VGO("Vigo–Peinador Airport","Vigo"),
    VRL("Vila Real Airport","Vila Real"),
    VHM("Vilhelmina Airport","Vilhelmina"),
    VNO("Vilnius Airport","Vilnius"),
    VBY("Visby Airport","Visby"),
    VSE("Viseu Airport[1]","Viseu"),
    VIT("Vitoria Airport","Vitoria-Gasteiz"),
    VTL("Vittel - Champ-de-Courses Airport[1]","Vittel"),
    SKS("Vojens Airport (Skrydstrup Airport)","Vojens"),
    VOL("Nea Anchialos National Airport","Volos"),
    WTN("RAF Waddington[1]","Waddington"),
    AGE("Wangerooge Airfield","Wangerooge"),
    WAW("Warsaw Chopin Airport","Warsaw"),
    WRT("Warton Aerodrome","Warton"),
    WAT("Waterford Airport","Waterford"),
    NRN("Weeze Airport (Niederrhein Airport)","Weeze"),
    WRY("Westray Airport[1]","Westray"),
    WHS("Whalsay Airstrip[1]","Whalsay"),
    WIC("Wick Airport","Wick"),
    WIE("Wiesbaden Army Airfield","Wiesbaden"),
    WVN("JadeWeserAirport","Wilhelmshaven"),
    WFD("Woodford Aerodrome[1]","Woodford"),
    WRO("Copernicus Airport Wrocław","Wrocław"),
    OHR("Wyk auf Föhr Airport[1]","Wyk auf Föhr"),
    QUY("RAF Wyton[1]","Wyton"),
    JAM("Bezmer Air Base","Yambol"),
    BBS("Blackbushe Airport","Yateley"),
    YEO("Royal Naval Air Station Yeovilton","Yeovilton"),
    YLI("Ylivieska Airfield","Ylivieska"),
    ZAD("Zadar Airport","Zadar"),
    ZAG("Franjo Tuđman Airport","Zagreb"),
    ZTH("Zakynthos International Airport (Dionysios SolomosAirport)","Zakynthos"),
    ZAZ("Zaragoza Airport","Zaragoza"),
    IEG("Zielona Góra Airport","Zielona Góra"),
    ILZ("Žilina Airport","Žilina"),
    GTW("Holešov Airport","Zlín"),
    OBL("Oostmalle Airfield","Zoersel"),
    ZRH("Zurich Airport","Zürich"),
    ZQW("Zweibrücken Airport","Zweibrücken");

    private String airportName;
    private String locationServed;


    Airports(String airportName, String locationServed) {
        this.airportName = airportName;
        this.locationServed = locationServed;
    }

    public String getLocationServed() {
        return locationServed;
    }

    public String getAirportName() {
        return airportName;
    }
}
