package org.academiadecodigo.codezillas.converters;

public enum Airports {
    LCG("A Coruña Airport","A Coruña,Spain"),
    AAH("Merzbrück Airport","Aachen,Germany"),
    AAL("Aalborg Airport","Aalborg,Denmark"),
    AAR("Aarhus Airport","Aarhus,Denmark"),
    ABZ("Aberdeen Airport","Aberdeen,United Kingdom"),
    AGF("Agen La Garenne Airport","Agen,France"),
    AGQ("Agrinion Airport","Agrinion,Greece"),
    AJA("Ajaccio Napoleon Bonaparte Airport","Ajaccio,France"),
    AKT("RAF Akrotiri","Akrotiri,Cyprus"),
    ABC("Albacete Airport","Albacete,Spain"),
    ALL("Albenga Airport","Albenga,Italy"),
    BYF("Albert – Picardie Airport[1]","Albert,France"),
    LBI("Le Sequestre Airport","Albi,France"),
    ACI("Alderney Airport","Alderney,United Kingdom"),
    AES("Ålesund Airport, Vigra","Ålesund,Norway"),
    AXD("Alexandroupoli Airport (Dimokritos Airport)","Alexandroupoli,Greece"),
    AHO("Alghero-Fertilia Airport","Alghero,Italy"),
    ALC("Alicante–Elche Airport","Alicante,Spain"),
    LEI("Almería Airport","Almería,Spain"),
    AHZ("Alpe d'Huez Airport","Alpe d'Huez,France"),
    ALF("Alta Airport","Alta,Norway"),
    AOC("Leipzig–Altenburg Airport","Altenburg,Germany"),
    ACH("St. Gallen–Altenrhein Airport","Altenrhein,Switzerland"),
    AMS("Amsterdam Airport Schiphol","Amsterdam,Netherlands"),
    AOI("Ancona Falconara Airport","Ancona,Italy"),
    ANX("Andøya Airport, Andenes","Andenes,Norway"),
    AGH("Ängelholm–Helsingborg Airport (former ICAO: ESDB)","Ängelholm,Sweden"),
    ANE("Angers – Loire Airport","Angers,France"),
    VLY("Anglesey Airport / RAF Valley","Anglesey,United Kingdom"),
    ANG("Angoulême – Cognac International Airport","Angoulême,France"),
    NCY("Annecy – Haute-Savoie – Mont Blanc Airport","Annecy,France"),
    ANR("Antwerp International Airport","Antwerp,Belgium"),
    AOT("Aosta Valley Airport","Aosta,Italy"),
    ARW("Arad International Airport","Arad,Romania"),
    AJR("Arvidsjaur Airport","Arvidsjaur,Sweden"),
    JTY("Astypalaia Island National Airport","Astypalaia,Greece"),
    ATH("Athens International Airport (Eleftherios Venizelos Airport)","Athens,Greece"),
    OBS("Aubenas Aerodrome[1] (Ardèche Méridionale Aerodrome)","Aubenas,France"),
    AGB("Augsburg Airport","Augsburg,Germany"),
    AUR("Aurillac – Tronquières Airport","Aurillac,France"),
    AUF("Auxerre – Branches Aerodrome","Auxerre,France"),
    AVB("Aviano Air Base","Aviano,Italy"),
    AVN("Avignon – Provence Airport","Avignon,France"),
    BCM("Bacău International Airport","Bacău,Romania"),
    BJZ("Badajoz Airport (Talavera la Real Air Base)","Badajoz,Spain"),
    BAY("Baia Mare Airport","Baia Mare,Romania"),
    BOL("Ballykelly Airfield (RAF Ballykelly)","Ballykelly,United Kingdom"),
    BMR("Baltrum Airport","Baltrum,Germany"),
    BYT("Bantry Aerodrome","Bantry,Ireland"),
    BCN("Barcelona–El Prat Airport","Barcelona,Spain"),
    BAE("Barcelonnette – Saint-Pons Airport","Barcelonnette,France"),
    BDU("Bardufoss Airport","Bardufoss,Norway"),
    BRI("Bari Karol Wojtyła Airport","Bari,Italy"),
    BRR("Barra Airport","Barra,United Kingdom"),
    BWF("Barrow/Walney Island Airport","Barrow-in-Furness,United Kingdom"),
    BSL("EuroAirport Basel-Mulhouse-Freiburg","Basel,Switzerland"),
    BIA("Bastia – Poretta Airport","Bastia,France"),
    BJF("Båtsfjord Airport","Båtsfjord,Norway"),
    BYU("Bindlacher Berg Airport","Bayreuth,Germany"),
    BVA("Beauvais–Tillé Airport","Beauvais,France"),
    BYJ("Beja Airport","Beja,Portugal"),
    BFS("Belfast International Airport","Belfast,United Kingdom"),
    BLX("Belluno Airport","Belluno,Italy"),
    BLY("Belmullet Aerodrome","Belmullet,Ireland"),
    BBP("Bembridge Airport","Bembridge,United Kingdom"),
    BEB("Benbecula Airport","Benbecula,United Kingdom"),
    BEX("RAF Benson","Benson,United Kingdom"),
    BGO("Bergen Airport, Flesland","Bergen,Norway"),
    WOE("Woensdrecht Air Base","Bergen op Zoom,Netherlands"),
    EGC("Bergerac Dordogne Périgord Airport","Bergerac,France"),
    BVG("Berlevåg Airport","Berlevåg,Norway"),
    TXL("Berlin Tegel Airport","Berlin,Germany"),
    BRN("Bern Airport","Bern,Switzerland"),
    BZR("Béziers Cap d'Agde Airport","Béziers,France"),
    BXP("Biała Podlaska Airport","Biała Podlaska,Poland"),
    BIQ("Biarritz Pays Basque Airport","Biarritz,France"),
    BFE("Bielefeld Airport","Bielefeld,Germany"),
    BIO("Bilbao Airport","Bilbao,Spain"),
    BLL("Billund Airport","Billund,Denmark"),
    BHX("Birmingham Airport","Birmingham,United Kingdom"),
    BBJ("Bitburg Airport (former Bitburg Air Base)","Bitburg,Germany"),
    BLK("Blackpool Airport","Blackpool,United Kingdom"),
    BOO("Bodø Airport","Bodø,Norway"),
    BWK("Bol Airport (Brač Airport)","Bol,Croatia"),
    BLQ("Bologna Guglielmo Marconi Airport","Bologna,Italy"),
    BZO("Bolzano Airport","Bolzano,Italy"),
    BOD("Bordeaux–Mérignac Airport","Bordeaux,France"),
    BMK("Borkum Airfield","Borkum,Germany"),
    BLE("Dala Airport (Borlänge Airport)","Borlänge,Sweden"),
    QXB("Aix les Milles, France","Bouches-du-Rhône,France"),
    BOU("Bourges Airport","Bourges,France"),
    BOH("Bournemouth Airport","Bournemouth,United Kingdom"),
    BGZ("Braga Airport","Braga,Portugal"),
    BGC("Bragança Airport","Bragança,Portugal"),
    LKZ("RAF Lakenheath","Brandon,United Kingdom"),
    BTS("M. R. Štefánik Airport","Bratislava,Slovakia"),
    BWE("Braunschweig–Wolfsburg Airport","Braunschweig,Germany"),
    GLZ("Gilze-Rijen Air Base","Breda,Netherlands"),
    BRE("Bremen Airport","Bremen,Germany"),
    BRV("Bremerhaven Airport","Bremerhaven,Germany"),
    VBS("Brescia Airport (Gabriele D'Annunzio Airport)","Brescia,Italy"),
    BES("Brest Bretagne Airport","Brest,France"),
    BDS("Brindisi – Salento Airport","Brindisi,Italy"),
    BRS("Bristol Airport","Bristol,United Kingdom"),
    BVE("Brive–Souillac Airport","Brive-la-Gaillarde,France"),
    BRQ("Brno–Tuřany Airport","Brno,Czech Republic"),
    BNN("Brønnøysund Airport, Brønnøy","Brønnøysund,Norway"),
    BRU("Brussels Airport (Zaventem Airport)","Brussels,Belgium"),
    OTP("Henri Coandă International Airport","Bucharest,Romania"),
    BUD("Budapest Ferenc Liszt International Airport","Budapest,Hungary"),
    BXO("Buochs Airport","Buochs,Switzerland"),
    URD("Burg Feuerstein Airport[1]","Burg Feuerstein,Germany"),
    BOJ("Burgas Airport","Burgas,Bulgaria"),
    RGS("Burgos Airport","Burgos,Spain"),
    BEQ("RAF Honington","Bury St Edmunds,United Kingdom"),
    BZG("Bydgoszcz Ignacy Jan Paderewski Airport","Bydgoszcz,Poland"),
    CFR("Caen – Carpiquet Airport","Caen,France"),
    CAG("Cagliari Elmas Airport","Cagliari,Italy"),
    ZAO("Cahors - Lalbenque Airport","Cahors,France"),
    CQF("Calais–Dunkerque Airport","Calais / Dunkirk,France"),
    CLY("Calvi – Sainte-Catherine Airport","Calvi,France"),
    CBG("Cambridge Airport","Cambridge,United Kingdom"),
    CAL("Campbeltown Airport / RAF Machrihanish","Campbeltown,United Kingdom"),
    CEQ("Cannes – Mandelieu Airport","Cannes,France"),
    CSB("Caransebeș Airport","Caransebeș,Romania"),
    CCF("Carcassonne Airport","Carcassonne,France"),
    CWL("Cardiff Airport","Cardiff,United Kingdom"),
    CAX("Carlisle Lake District Airport","Carlisle,United Kingdom"),
    BZZ("RAF Brize Norton","Carterton,United Kingdom"),
    CAT("Cascais Municipal Aerodrome[1]","Cascais,Portugal"),
    CDT("Castellón–Costa Azahar Airport","Castellón de la Plana,Spain"),
    DCM("Castres–Mazamet Airport","Castres,France"),
    CTA("Catania–Fontanarossa Airport","Catania,Italy"),
    EFL("Cephalonia International Airport","Cephalonia,Greece"),
    XCR("Châlons Vatry Airport","Châlons-en-Champagne,France"),
    CMF("Chambéry-Savoie Airport","Chambéry,France"),
    CHQ("Chania International Airport","Chania,Greece"),
    CRL("Brussels South Charleroi Airport","Charleroi,Belgium"),
    CHR("Châteauroux-Centre Marcel Dassault Airport","Châteauroux,France"),
    CHV("Chaves Airport","Chaves,Portugal"),
    CER("Cherbourg – Maupertus Airport","Cherbourg-Octeville,France"),
    CEG("Hawarden Airport (Chester Airport)","Chester,United Kingdom"),
    QUG("Chichester/Goodwood Airport","Chichester,United Kingdom"),
    JKH("Chios Island National Airport","Chios,Greece"),
    CET("Cholet Le Pontreau Airport","Cholet,France"),
    CQM("Ciudad Real Central Airport","Ciudad Real,Spain"),
    CFE("Clermont-Ferrand Auvergne Airport","Clermont-Ferrand,France"),
    VAC("Varrelbusch Airport[1]","Cloppenburg,Germany"),
    CLJ("Cluj-Napoca International Airport","Cluj-Napoca,Romania"),
    CNG("Cognac – Châteaubernard Air Base","Cognac,France"),
    CBP("Coimbra Airport","Coimbra,Portugal"),
    COL("Coll Airport","Coll,United Kingdom"),
    CMR("Colmar – Houssen Airport","Colmar,France"),
    CGN("Cologne Bonn Airport","Cologne / Bonn,Germany"),
    CSA("Colonsay Airport","Colonsay,United Kingdom"),
    CIY("Comiso Airport","Comiso,Italy"),
    QCY("RAF Coningsby","Coningsby,United Kingdom"),
    CND("Mihail Kogălniceanu International Airport","Constanța,Romania"),
    CPH("Copenhagen Airport, Kastrup","Copenhagen,Denmark"),
    ODB("Córdoba Airport","Córdoba,Spain"),
    CFU("Corfu International Airport (Ioannis Kapodistrias Int'l Airport)","Corfu,Greece"),
    ORK("Cork Airport","Cork,Ireland"),
    CVU("Corvo Airport","Corvo Island,Portugal"),
    CBU("Cottbus-Drewitz Airport","Cottbus,Germany"),
    CVF("Courchevel Altiport","Courchevel,France"),
    CVT("Coventry Airport","Coventry,United Kingdom"),
    CRA("Craiova International Airport","Craiova,Romania"),
    CSF("Creil Air Base","Creil,France"),
    CRV("Crotone Airport (Sant'Anna Airport)","Crotone,Italy"),
    CUF("Cuneo International Airport","Cuneo,Italy"),
    FCN("Nordholz Naval Airbase","Cuxhaven,Germany"),
    CZW("Częstochowa-Rudniki Airport","Częstochowa,Poland"),
    DGP("Daugavpils International Airport","Daugavpils,Latvia"),
    DOL("Deauville – Saint-Gatien Airport","Deauville,France"),
    DEB("Debrecen International Airport","Debrecen,Hungary"),
    DCI("Decimomannu Air Base","Decimomannu,Italy"),
    DHR("De Kooy Airfield","Den Helder,Netherlands"),
    LDY("City of Derry Airport","Derry (Londonderry),United Kingdom"),
    DPE("Dieppe - Saint-Aubin Airport","Dieppe,France"),
    DIJ("Dijon Air Base","Dijon,France"),
    DNR("Dinard–Pleurtuit–Saint-Malo Airport","Dinard / Saint-Malo,France"),
    DLE("Dole–Jura Airport","Dole,France"),
    ZBE("Zábřeh Airport","Dolní Benešov,Czech Republic"),
    DSA("Robin Hood Airport Doncaster Sheffield","Doncaster,United Kingdom"),
    CFN("Donegal Airport","Donegal,Ireland"),
    HOH("Hohenems-Dornbirn Airport","Dornbirn,Austria"),
    DOC("Dornoch Airport","Dornoch,United Kingdom"),
    DTM("Dortmund Airport","Dortmund,Germany"),
    DRS("Dresden Airport","Dresden,Germany"),
    DUB("Dublin Airport","Dublin,Ireland"),
    DBV("Dubrovnik Airport","Dubrovnik,Croatia"),
    DND("Dundee Airport","Dundee,United Kingdom"),
    DUS("Düsseldorf Airport","Düsseldorf,Germany"),
    EOI("Eday Airport","Eday,United Kingdom"),
    EDI("Edinburgh Airport","Edinburgh,United Kingdom"),
    EIN("Eindhoven Airport","Eindhoven,Netherlands"),
    EIB("Eisenach-Kindel Airport[1]","Eisenach,Germany"),
    EBA("Marina di Campo Airport","Elba Island,Italy"),
    EME("Emden Airport","Emden,Germany"),
    EML("Emmen Air Base","Emmen,Switzerland"),
    ENK("Enniskillen/St Angelo Airport","Enniskillen,United Kingdom"),
    ENF("Enontekiö Airport","Enontekiö,Finland"),
    ENS("Enschede Airport Twente","Enschede,Netherlands"),
    EPL("Épinal – Mirecourt Airport","Épinal / Mirecourt,France"),
    ERF("Erfurt–Weimar Airport","Erfurt,Germany"),
    EBJ("Esbjerg Airport","Esbjerg,Denmark"),
    EKT("Eskilstuna Airport","Eskilstuna,Sweden"),
    ESS("Essen/Mülheim Airport","Essen,Germany"),
    EVX("Évreux-Fauville Air Base","Évreux,France"),
    EXT("Exeter International Airport","Exeter,United Kingdom"),
    VDB("Fagernes Airport, Leirin","Fagernes,Norway"),
    FIE("Fair Isle Airport","Fair Isle,United Kingdom"),
    FFD("RAF Fairford","Fairford,United Kingdom"),
    FAB("Farnborough Airport","Farnborough,United Kingdom"),
    FAO("Faro Airport","Faro,Portugal"),
    FEA("Fetlar Airport","Fetlar,United Kingdom"),
    FSC("Figari–Sud Corse Airport","Figari,France"),
    FLF("Flensburg-Schäferhaus Airport","Flensburg,Germany"),
    FLR("Florence Airport, Peretola (Amerigo Vespucci Airport)","Florence,Italy"),
    FLW("Flores Airport","Flores Island,Portugal"),
    FRO("Florø Airport","Florø,Norway"),
    FLH("Flotta Island Airport","Flotta,United Kingdom"),
    FOG("Foggia Gino Lisa Airport","Foggia,Italy"),
    FDE("Førde Airport, Bringeland","Førde,Norway"),
    FRL("Forlì International Airport (Luigi Ridolfi Airport)","Forlì,Italy"),
    FSS("RAF Kinloss","Forres,United Kingdom"),
    FOA("Foula Airfield","Foula,United Kingdom"),
    FRA("Frankfurt Airport","Frankfurt,Germany"),
    FDH("Friedrichshafen Airport (Bodensee Airport)","Friedrichshafen,Germany"),
    FRZ("Fritzlar Air Base","Fritzlar,Germany"),
    FUE("Fuerteventura Airport","Fuerteventura,Spain"),
    FNC("Madeira Airport","Funchal,Portugal"),
    FEL("Fürstenfeldbruck Air Base","Fürstenfeldbruck,Germany"),
    GEV("Gällivare Airport","Gällivare,Sweden"),
    GWY("Galway Airport","Galway,Ireland"),
    GAT("Gap–Tallard Airport","Gap,France"),
    GVX("Gävle-Sandviken Airport","Gävle,Sweden"),
    GDN("Gdańsk Lech Wałęsa Airport","Gdańsk,Poland"),
    GEC("Geçitkale Air Base","Geçitkale,Northern Cyprus"),
    GKE("NATO Air Base Geilenkirchen","Geilenkirchen,Germany"),
    GVA("Geneva Airport","Geneva,Switzerland"),
    GOA("Genoa Cristoforo Colombo Airport","Genoa,Italy"),
    GHF("Giebelstadt Airport","Giebelstadt,Germany"),
    GRO("Girona–Costa Brava Airport","Girona,Spain"),
    PIK("Glasgow Prestwick Airport","Glasgow,United Kingdom"),
    GLO("Gloucestershire Airport","Gloucester / Cheltenham,United Kingdom"),
    GLL("Gol Airport, Klanten","Gol,Norway"),
    GOZ("Gorna Oryahovitsa Airport","Gorna Oryahovitsa,Bulgaria"),
    GOT("Göteborg Landvetter Airport","Gothenburg,Sweden"),
    GRW("Graciosa Airport","Graciosa,Portugal"),
    LPA("Gran Canaria Airport","Gran Canaria,Spain"),
    GRX("Federico García Lorca Airport (Granada Jaén Airport)","Granada,Spain"),
    GFR("Granville–Mont-Saint-Michel Aerodrome [fr]","Granville,France"),
    GRZ("Graz Airport","Graz,Austria"),
    LHB("Bruntingthorpe Aerodrome (Leicester Harboro'/Harbour Airport)","Greater Leicester,United Kingdom"),
    GNB("Grenoble–Isère Airport","Grenoble,France"),
    GRQ("Groningen Airport Eelde","Groningen,Netherlands"),
    GRS("Grosseto Airport","Grosseto,Italy"),
    GCI("Guernsey Airport","Guernsey,United Kingdom"),
    GUT("RAF Gütersloh","Gütersloh,Germany"),
    GTI("Rügen Airport (Güttin Airfield)","Güttin,Germany"),
    HFS("Hagfors Airport","Hagfors,Sweden"),
    HHN("Frankfurt–Hahn Airport","Hahn,Germany"),
    HAD("Halmstad Airport (Halmstad City Airport)","Halmstad,Sweden"),
    HMR("Hamar Airport, Stafsberg","Hamar,Norway"),
    HAM("Hamburg Airport","Hamburg,Germany"),
    HFT("Hammerfest Airport","Hammerfest,Norway"),
    HAJ("Hannover Airport","Hanover,Germany"),
    EVE("Harstad/Narvik Airport, Evenes","Harstad / Narvik,Norway"),
    HKV("Haskovo Malevo Airport","Haskovo,Bulgaria"),
    HAA("Hasvik Airport","Hasvik,Norway"),
    HAU("Haugesund Airport, Karmøy","Haugesund,Norway"),
    HAW("Haverfordwest Aerodrome","Haverfordwest,United Kingdom"),
    HZB("Merville–Calonne Airport","Hazebrouck,France"),
    HEI("Heide–Büsum Airport","Heide / Büsum,Germany"),
    HDB("Heidelberg Airport","Heidelberg,Germany"),
    HGL("Heligoland Airport (Düne Airport)","Heligoland,Germany"),
    HEL("Helsinki Airport (Helsinki-Vantaa Airport)","Helsinki,Finland"),
    HMV("Hemavan Tärnaby Airport","Hemavan / Tärnaby,Sweden"),
    HER("Heraklion International Airport (Nikos Kazantzakis Airport)","Heraklion,Greece"),
    HDF("Heringsdorf Airport","Heringsdorf,Germany"),
    SOB("Hévíz–Balaton Airport","Hévíz,Hungary"),
    HYC("Wycombe Air Park","High Wycombe,United Kingdom"),
    HOQ("Hof–Plauen Airport","Hof,Germany"),
    HVG("Honningsvåg Airport, Valan","Honningsvåg,Norway"),
    HOR("Horta Airport","Horta,Portugal"),
    HUV("Hudiksvall Airport","Hudiksvall,Sweden"),
    HSK("Huesca–Pirineos Airport","Huesca,Spain"),
    HLF("Hultsfred-Vimmerby Airport","Hultsfred / Vimmerby,Sweden"),
    QHU("Husum Schwesing Airport[1]","Husum,Germany"),
    HYV("Hyvinkää Airfield","Hyvinkää,Finland"),
    IAS("Iași International Airport","Iași,Romania"),
    IBZ("Ibiza Airport","Ibiza,Spain"),
    IDB("Idre Airport","Idre,Sweden"),
    JIK("Ikaria Island National Airport","Ikaria Island,Greece"),
    IDY("Île d'Yeu Aerodrome","Île d'Yeu,France"),
    ILH("Illesheim Army Airfield","Illesheim,Germany"),
    IGS("Ingolstadt Manching Airport","Ingolstadt,Germany"),
    INQ("Inisheer Aerodrome","Inisheer,Ireland"),
    IIA("Inishmaan Aerodrome","Inishmaan,Ireland"),
    IOR("Inishmore Aerodrome (Kilronan Airport)","Inishmore,Ireland"),
    INN("Innsbruck Airport (Kranebitten Airport)","Innsbruck,Austria"),
    INV("Inverness Airport","Inverness,United Kingdom"),
    IOA("Ioannina National Airport","Ioannina,Greece"),
    ILY("Islay Airport (Glenegedale Airport)","Islay,United Kingdom"),
    IOM("Isle of Man Airport (Ronaldsway Airport)","Isle of Man,United Kingdom"),
    SKL("Broadford Airfield[1]","Isle of Skye,United Kingdom"),
    IVL("Ivalo Airport","Ivalo,Finland"),
    XRY("Jerez Airport (La Parra Airport)","Jerez de la Frontera,Spain"),
    JER("Jersey Airport","Jersey,United Kingdom"),
    JOE("Joensuu Airport","Joensuu,Finland"),
    JKG("Jönköping Airport","Jönköping,Sweden"),
    JUI("Juist Airport","Juist,Germany"),
    JYV("Jyväskylä Airport","Jyväskylä,Finland"),
    KAJ("Kajaani Airport","Kajaani,Finland"),
    KLX("Kalamata International Airport","Kalamata,Greece"),
    KLR("Kalmar Airport","Kalmar,Sweden"),
    JKL("Kalymnos Island National Airport","Kalymnos,Greece"),
    KDL("Kärdla Airport","Kärdla,Estonia"),
    KLV("Karlovy Vary Airport","Karlovy Vary,Czech Republic"),
    KSK("Karlskoga Airport","Karlskoga,Sweden"),
    FKB("Karlsruhe/Baden-Baden Airport","Karlsruhe / Baden-Baden,Germany"),
    KSD("Karlstad Airport","Karlstad,Sweden"),
    AOK("Karpathos Island National Airport","Karpathos,Greece"),
    KRP("Karup Airport","Karup,Denmark"),
    KSJ("Kasos Island Public Airport","Kasos Island,Greece"),
    KSF("Kassel Airport","Kassel,Germany"),
    KZS("Kastellorizo Island Public Airport","Kastellorizo,Greece"),
    KSO("Kastoria National Airport (Aristotelis Airport)","Kastoria,Greece"),
    KTW("Katowice International Airport","Katowice,Poland"),
    KHJ("Kauhajoki Airfield","Kauhajoki,Finland"),
    KAU("Kauhava Airfield","Kauhava,Finland"),
    KUN("Kaunas International Airport","Kaunas,Lithuania"),
    KVA("Kavala International Airport (Alexander the Great Airport)","Kavala,Greece"),
    GBA("Cotswold Airport[2]","Kemble,United Kingdom"),
    KEM("Kemi-Tornio Airport","Kemi / Tornio,Finland"),
    KIR("Kerry Airport (Farranfore Airport)","Kerry,Ireland"),
    KEL("Kiel Airport","Kiel,Germany"),
    KKY("Kilkenny Airport","Kilkenny,Ireland"),
    KNF("RAF Marham","King's Lynn,United Kingdom"),
    HUY("Humberside Airport","Kingston upon Hull,United Kingdom"),
    KKN("Kirkenes Airport, Høybuktmoen","Kirkenes,Norway"),
    KOI("Kirkwall Airport","Kirkwall,United Kingdom"),
    KRN("Kiruna Airport","Kiruna,Sweden"),
    KTQ("Kitee Airfield","Kitee,Finland"),
    KTT("Kittilä Airport","Kittilä,Finland"),
    KZG("Kitzingen Airport","Kitzingen,Germany"),
    KLU("Klagenfurt Airport","Klagenfurt,Austria"),
    NOC("Ireland West Airport Knock","Knock,Ireland"),
    KOK("Kokkola-Pietarsaari Airport","Kokkola / Jakobstad,Finland"),
    KJK("Kortrijk–Wevelgem International Airport","Kortrijk,Belgium"),
    KGS("Kos Island International Airport","Kos,Greece"),
    KSC("Košice International Airport","Košice,Slovakia"),
    OSZ("Koszalin-Zegrze Pomorskie Airport[1]","Koszalin,Poland"),
    KOQ("Köthen Airport","Köthen,Germany"),
    KZI("Kozani National Airport (Filippos Airport)","Kozani,Greece"),
    KRK("John Paul II International Airport Kraków–Balice","Kraków,Poland"),
    KRF("Höga Kusten Airport (Kramfors-Sollefteå Airport)","Kramfors / Sollefteå,Sweden"),
    KRS("Kristiansand Airport, Kjevik","Kristiansand,Norway"),
    KID("Kristianstad Airport","Kristianstad,Sweden"),
    KSU("Kristiansund Airport, Kvernberget","Kristiansund,Norway"),
    KUO("Kuopio Airport","Kuopio,Finland"),
    KEV("Halli Airport","Kuorevesi,Finland"),
    URE("Kuressaare Airport","Kuressaare,Estonia"),
    KAO("Kuusamo Airport","Kuusamo,Finland"),
    KIT("Kithira Island National Airport","Kythira,Greece"),
    QAQ("L'Aquila–Preturo Airport[1]","L'Aquila,Italy"),
    LBY("La Baule-Escoublac Airport","La Baule-Escoublac,France"),
    GMZ("La Gomera Airport","La Gomera / Canary Islands,Spain"),
    SPC("La Palma Airport","La Palma,Spain"),
    EDM("La Roche-sur-Yon Aerodrome","La Roche-sur-Yon,France"),
    LRH("La Rochelle – Île de Ré Airport","La Rochelle,France"),
    LEU("La Seu d'Urgell Airport","La Seu d'Urgell,Spain"),
    BYR("Læsø Airport","Læsø,Denmark"),
    LHA("Flughafen Lahr (Lahr Airport)","Lahr,Germany"),
    LKL("Lakselv Airport, Banak","Lakselv,Norway"),
    SUF("Lamezia Terme International Airport","Lamezia Terme,Italy"),
    LMP("Lampedusa Airport","Lampedusa,Italy"),
    LDV("Landivisiau Air Base","Landivisiau,France"),
    LGO("Langeoog Airport","Langeoog,Germany"),
    LAI("Lannion – Côte de Granit Airport","Lannion,France"),
    ACE("Lanzarote Airport","Lanzarote,Spain"),
    LPP("Lappeenranta Airport","Lappeenranta,Finland"),
    LRA("Larissa National Airport","Larissa,Greece"),
    LCA("Larnaca International Airport","Larnaca,Cyprus"),
    LVA("Laval Entrammes Airport","Laval,France"),
    CTT("Le Castellet Airport","Le Castellet,France"),
    LEH("Le Havre – Octeville Airport","Le Havre,France"),
    LME("Le Mans Arnage Airport","Le Mans,France"),
    LPY("Le Puy – Loudes Airport","Le Puy-en-Velay,France"),
    LTQ("Le Touquet – Côte d'Opale Airport","Le Touquet-Paris-Plage,France"),
    LCC("Galatina Air Base","Lecce,Italy"),
    LBA("Leeds Bradford Airport","Leeds / Bradford,United Kingdom"),
    LWR("Leeuwarden Air Base","Leeuwarden,Netherlands"),
    LRC("Leicester City Airport","Leicester,United Kingdom"),
    LEJ("Leipzig/Halle Airport","Leipzig,2 Germany"),
    LKN("Leknes Airport","Leknes,Norway"),
    LEY("Lelystad Airport","Lelystad,Netherlands"),
    LXS("Lemnos International Airport","Lemnos (Limnos),Greece"),
    XLW("Lemwerder Airport","Lemwerder,Germany"),
    LEN("León Airport","León,Spain"),
    LRS("Leros Municipal Airport","Leros,Greece"),
    LWK("Tingwall Airport (Lerwick/Tingwall Airport)","Lerwick,United Kingdom"),
    LSO("Les Sables-d'Olonne – Talmont Airport","Les Sables-d'Olonne,France"),
    LTR("Letterkenny Airfield","Letterkenny,Ireland"),
    LDK("Lidköping-Hovby Airport","Lidköping,Sweden"),
    LGG("Liège Airport","Liège,Belgium"),
    LPX("Liepāja International Airport","Liepāja,Latvia"),
    LIL("Lille Airport (Lille–Lesquin Airport)","Lille,France"),
    LIG("Limoges – Bellegarde Airport","Limoges,France"),
    LPI("Linköping/Saab Airport","Linköping,Sweden"),
    HRT("RAF Linton-on-Ouse","Linton-on-Ouse,United Kingdom"),
    LNZ("Linz Airport (Blue Danube Airport)","Linz,Austria"),
    LIS("Lisbon Portela Airport","Lisbon,Portugal"),
    LPL("Liverpool John Lennon Airport","Liverpool,United Kingdom"),
    LJU("Ljubljana Jože Pučnik Airport (Brnik Airport)","Ljubljana,Slovenia"),
    ILD("Lleida–Alguaire Airport","Lleida,Spain"),
    LCJ("Łódź Władysław Reymont Airport","Łódź,Poland"),
    RJL("Logroño–Agoncillo Airport","Logroño,Spain"),
    LHR("Heathrow Airport","London,United Kingdom"),
    BQH("London Biggin Hill Airport","London / Biggin Hill,United Kingdom"),
    SEN("London Southend Airport","London / Southend,United Kingdom"),
    HOY("Hoy Island Airport","Longhope,United Kingdom"),
    LYR("Svalbard Airport, Longyear","Longyearbyen,Norway"),
    LRT("Lorient South Brittany Airport (Lann-Bihoué Airport)","Lorient,France"),
    LSZ("Lošinj Airport","Lošinj,Croatia"),
    LMO("RAF Lossiemouth","Lossiemouth,United Kingdom"),
    LBC("Lübeck Airport","Lübeck,Germany"),
    LUZ("Lublin Airport","Lublin,Poland"),
    LCV("Lucca-Tassignano Airport","Lucca,Italy"),
    LUE("Boľkovce Airport","Lučenec,Slovakia"),
    LUG("Lugano Airport","Lugano,Switzerland"),
    LLA("Luleå Airport (Kallax Airport)","Luleå,Sweden"),
    MLA("Malta International Airport (Luqa Airport)","Luqa,Malta"),
    LUX("Luxembourg Findel Airport","Luxembourg,Luxembourg"),
    LYC("Lycksele Airport","Lycksele,Sweden"),
    LYX("Lydd Airport (London Ashford Airport)","Lydd,United Kingdom"),
    LYE("RAF Lyneham","Lyneham,United Kingdom"),
    LYS("Lyon–Saint-Exupéry Airport","Lyon,France"),
    MST("Maastricht Aachen Airport","Maastricht,Netherlands"),
    MAD("Adolfo Suárez Madrid–Barajas Airport","Madrid,Spain"),
    CSO("Magdeburg–Cochstedt Airport","Magdeburg,Germany"),
    AGP("Málaga Airport","Málaga,Spain"),
    MMX("Malmö Airport","Malmö,Sweden"),
    MAN("Manchester Airport","Manchester,United Kingdom"),
    MHG("Mannheim City Airport","Mannheim,Germany"),
    MSE("Manston Airport (Kent International Airport)","Manston,United Kingdom"),
    MKA("Mariánské Lázně Airport","Mariánské Lázně,Czech Republic"),
    MRW("Lolland Falster Airport","Maribo,Denmark"),
    MBX("Maribor Edvard Rusjan Airport","Maribor,Slovenia"),
    MHQ("Mariehamn Airport","Mariehamn,Finland"),
    MRS("Marseille Provence Airport","Marseille,France"),
    MVV("Megève Altiport","Megève,France"),
    MEH("Mehamn Airport","Mehamn,Norway"),
    MLN("Melilla Airport","Melilla,Spain"),
    FMM("Memmingen Airport","Memmingen,Germany"),
    MEN("Brenoux Airport","Mende,France"),
    MAH("Menorca Airport (Mahón Airport)","Menorca,Spain"),
    MFX("Méribel Altiport","Méribel,France"),
    MZM("Metz-Frescaty Air Base","Metz,France"),
    ETZ("Metz–Nancy–Lorraine Airport","Metz / Nancy,France"),
    MIK("Mikkeli Airport","Mikkeli,Finland"),
    MXP("Milan–Malpensa Airport","Milan,Italy"),
    BGY("Il Caravaggio International Airport (Orio al Serio Airport)","Milan / Bergamo,Italy"),
    MHZ("RAF Mildenhall","Mildenhall,United Kingdom"),
    MLO("Milos Island National Airport","Milos,Greece"),
    MCQ("Miskolc Airport","Miskolc,Hungary"),
    MQN("Mo i Rana Airport, Røssvoll","Mo i Rana,Norway"),
    MOL("Molde Airport, Årø","Molde,Norway"),
    MGL("Düsseldorf Mönchengladbach Airport","Mönchengladbach,Germany"),
    SCP("Mont-Dauphin - Saint-Crépin Airport[1]","Mont-Dauphin,France"),
    MCU("Montluçon – Guéret Airport","Montluçon,France"),
    MPL("Montpellier–Méditerranée Airport (Fréjorgues Airport)","Montpellier,France"),
    MXX("Mora–Siljan Airport","Mora,Sweden"),
    MXN("Morlaix – Ploujean Airport","Morlaix,France"),
    OZP("Morón Air Base[1]","Morón de la Frontera,Spain"),
    MJF("Mosjøen Airport, Kjærstad","Mosjøen,Norway"),
    MLH("EuroAirport Basel Mulhouse Freiburg","Mulhouse,France"),
    ULL("Glenforsa Airfield[1]","Mull,United Kingdom"),
    MUC("Munich Airport","Munich,Germany"),
    FMO("Münster Osnabrück International Airport","Münster / Osnabrück (LS),Germany"),
    MJV("Murcia–San Javier Airport","Murcia,Spain"),
    RMU("Región de Murcia International Airport[1]","Murcia / Cartagena,Spain"),
    JMK("Mykonos Island National Airport","Mykonos,Greece"),
    MJT("Mytilene International Airport","Mytilene,Greece"),
    OSY("Namsos Airport, Høknesøra","Namsos,Norway"),
    ENC("Nancy-Essey Airport","Nancy,France"),
    NTE("Nantes Atlantique Airport","Nantes,France"),
    NAP("Naples International Airport","Naples,Italy"),
    NVK("Narvik Airport, Framnes","Narvik,Norway"),
    JNX("Naxos Island National Airport","Naxos,Greece"),
    FNB("Neubrandenburg Airport","Neubrandenburg,Germany"),
    EUM("Neumünster Airport","Neumünster,Germany"),
    NVS("Nevers - Fourchambault Airport[1]","Nevers,France"),
    NCL("Newcastle Airport","Newcastle upon Tyne,United Kingdom"),
    NQY("Newquay Airport","Newquay,United Kingdom"),
    NCE("Nice Côte d'Azur Airport","Nice,France"),
    NIC("Nicosia International Airport1","Nicosia,Cyprus"),
    ECN("Ercan International Airport[1]","Nicosia (Lefkoşa),Northern Cyprus"),
    FNI("Nîmes–Alès–Camargue–Cévennes Airport (Garons Airport)","Nîmes,France"),
    NIT("Niort - Souché Airport[1]","Niort,France"),
    NOD("Norddeich Airport","Norden,Germany"),
    NRD("Norderney Airport","Norderney,Germany"),
    NRK("Norrköping Airport","Norrköping,Sweden"),
    NRL("North Ronaldsay Airport[1]","North Ronaldsay,United Kingdom"),
    ORM("Sywell Aerodrome","Northampton,United Kingdom"),
    NHT("RAF Northolt","Northolt,United Kingdom"),
    NWI("Norwich International Airport","Norwich,United Kingdom"),
    NTB("Notodden Airport, Tuven","Notodden,Norway"),
    NQT("Nottingham Airport[1]","Nottingham,United Kingdom"),
    EMA("East Midlands Airport","Nottingham / Leicester / Derby,United Kingdom"),
    NUE("Nuremberg Airport","Nuremberg,Germany"),
    OKH("RAF Cottesmore","Oakham,United Kingdom"),
    OBN("Oban Airport[1] (North Connel Airport)","Oban,United Kingdom"),
    OBF("Oberpfaffenhofen Airport","Oberpfaffenhofen,Germany"),
    ODE("Hans Christian Andersen Airport","Odense,Denmark"),
    ODH("RAF Odiham","Odiham,United Kingdom"),
    OLB("Olbia Costa Smeralda Airport","Olbia,Italy"),
    OLO("Olomouc Airport (Neředín Airport)","Olomouc,Czech Republic"),
    ZHZ("Halle-Oppin Airport","Oppin,Germany"),
    OMR("Oradea International Airport","Oradea,Romania"),
    ORB("Örebro Airport","Örebro,Sweden"),
    FNU("Oristano-Fenosu Airport[1]","Oristano,Italy"),
    OLA("Ørland Airport[1]","Ørland,Norway"),
    ORE("Orléans – Saint-Denis-de-l'Hôtel Airport[1]","Orléans,France"),
    OER("Örnsköldsvik Airport","Örnsköldsvik,Sweden"),
    HOV("Ørsta–Volda Airport, Hovden","Ørsta / Volda,Norway"),
    OSI("Osijek Airport","Osijek,Croatia"),
    OSK("Oskarshamn Airport","Oskarshamn,Sweden"),
    OSL("Oslo Airport, Gardermoen","Oslo,Norway"),
    RYG("Moss Airport, Rygge / Rygge Air Station","Oslo / Moss,Norway"),
    OST("Ostend–Bruges International Airport","Ostend / Bruges,Belgium"),
    OSD("Åre Östersund Airport","Östersund,Sweden"),
    OSR("Leoš Janáček Airport Ostrava","Ostrava,Czech Republic"),
    OUL("Oulu Airport","Oulu,Finland"),
    OUK("Out Skerries Airport[1]","Out Skerries,United Kingdom"),
    OVD("Asturias Airport (Oviedo Airport)","Oviedo,Spain"),
    OXF("Oxford Airport (London Oxford Airport)","Oxford,United Kingdom"),
    PAD("Paderborn Lippstadt Airport","Paderborn / Lippstadt,Germany"),
    PJA("Pajala Airport","Pajala,Sweden"),
    PLQ("Palanga International Airport","Palanga,Lithuania"),
    PMO("Falcone–Borsellino Airport (Punta Raisi Airport)","Palermo,Italy"),
    PMI("Palma de Mallorca Airport","Palma de Mallorca,Spain"),
    PNA("Pamplona Airport","Pamplona,Spain"),
    PNV("Panevėžys Air Base[1] (Pajuostis Airport)","Panevėžys,Lithuania"),
    PNL("Pantelleria Airport[1]","Pantelleria,Italy"),
    PSV("Papa Stour Airport[1]","Papa Stour,United Kingdom"),
    PPW("Papa Westray Airport","Papa Westray,United Kingdom"),
    PFO("Paphos International Airport","Paphos,Cyprus"),
    PED("Pardubice Airport","Pardubice,Czech Republic"),
    CDG("Charles de Gaulle Airport (Roissy Airport)","Paris,France"),
    PMF("Parma Airport (Giuseppe Verdi Airport)","Parma,Italy"),
    EPU("Pärnu Airport","Pärnu,Estonia"),
    PAS("Paros National Airport","Paros,Greece"),
    GPA("Araxos Airport","Patras,Greece"),
    PUF("Pau Pyrénées Airport","Pau,France"),
    PEV("Pécs-Pogány International Airport[1]","Pécs,Hungary"),
    PEF("Peenemünde Airfield[1]","Peenemünde,Germany"),
    PGX("Périgueux Bassillac Airport","Périgueux,France"),
    PGF("Perpignan–Rivesaltes Airport","Perpignan,France"),
    PSL("Perth Airport (Scone Airport)","Perth,United Kingdom"),
    PEG("Perugia San Francesco d'Assisi – Umbria International Airport","Perugia,Italy"),
    PSR("Abruzzo Airport","Pescara,Italy"),
    PIX("Pico Airport","Pico Island,Portugal"),
    PZY("Piešťany Airport","Piešťany,Slovakia"),
    PSA("Pisa International Airport (Galileo Galilei Airport)","Pisa,Italy"),
    PDV("Plovdiv Airport","Plovdiv,Bulgaria"),
    PLH("Plymouth City Airport","Plymouth,United Kingdom"),
    PIS("Poitiers–Biard Airport","Poitiers,France"),
    PDL("João Paulo II Airport","Ponta Delgada,Portugal"),
    TAT("Poprad–Tatry Airport","Poprad,Slovakia"),
    POR("Pori Airport","Pori,Finland"),
    PRM("Portimão Airport","Portimão,Portugal"),
    OPO("Francisco de Sá Carneiro Airport","Porto,Portugal"),
    PKH("Porto Cheli Airport","Porto Cheli (Portochelion),Greece"),
    PXO("Porto Santo Airport","Porto Santo Island,Portugal"),
    POW("Portorož Airport","Portorož,Slovenia"),
    POZ("Poznań–Ławica Airport","Poznań,Poland"),
    PRG("Václav Havel Airport Prague","Prague,Czech Republic"),
    PRV("Přerov Airport[1]","Přerov,Czech Republic"),
    POV("Prešov Air Base[1]","Prešov,Slovakia"),
    PVK("Aktion National Airport","Preveza / Lefkada,Greece"),
    PRP("Propriano Airport","Propriano,France"),
    PUY("Pula Airport","Pula,Croatia"),
    PYR("Andravida Air Base[1]","Pyrgos,Greece"),
    UIP("Quimper–Cornouaille Airport (Pluguffan)","Quimper,France"),
    RDO("Radom Airport[1]","Radom,Poland"),
    RMS("Ramstein Air Base","Ramstein,Germany"),
    RAN("Ravenna Airport[1]","Ravenna,Italy"),
    REB("Rechlin–Lärz Airfield[1]","Rechlin,Germany"),
    REG("Reggio di Calabria Airport","Reggio di Calabria,Italy"),
    RHE("Reims – Champagne Air Base","Reims,France"),
    RNS("Rennes–Saint-Jacques Airport","Rennes,France"),
    REU("Reus Airport","Reus,Spain"),
    RHO("Rhodes International Airport","Rhodes,Greece"),
    IES("Riesa–Göhlis Airfield","Riesa,Germany"),
    RIX("Riga International Airport","Riga,Latvia"),
    RJK("Rijeka Airport","Rijeka,Croatia"),
    RMI("Federico Fellini International Airport","Rimini,Italy"),
    RNE("Roanne Renaison Airport","Roanne,France"),
    RCO("Rochefort – Saint-Agnant Airport[1]","Rochefort,France"),
    RCS("Rochester Airport","Rochester,United Kingdom"),
    RDZ("Rodez–Marcillac Airport","Rodez,France"),
    FCO("Leonardo da Vinci–Fiumicino Airport","Rome,Italy"),
    RNN("Bornholm Airport","Rønne,Denmark"),
    RNB("Ronneby Airport","Ronneby / Karlskrona,Sweden"),
    RRS("Røros Airport","Røros,Norway"),
    RVK("Rørvik Airport, Ryum","Rørvik,Norway"),
    RET("Røst Airport","Røst,Norway"),
    RLG("Rostock–Laage Airport","Rostock,Germany"),
    ROZ("US Naval Station Rota[1]","Rota,Spain"),
    RTM("Rotterdam The Hague Airport","Rotterdam,Netherlands"),
    URO("Rouen Airport (Vallée de Seine Airport)","Rouen,France"),
    RVN("Rovaniemi Airport","Rovaniemi,Finland"),
    RYN("Royan – Médis Aerodrome","Royan,France"),
    ROU("Ruse Airport","Ruse,Bulgaria"),
    RZE("Rzeszów–Jasionka Airport","Rzeszów,Poland"),
    SCN("Saarbrücken Airport","Saarbrücken,Germany"),
    SBK("Saint-Brieuc – Armor Airport","Saint-Brieuc,France"),
    EBU("Saint-Étienne–Bouthéon Airport","Saint-Étienne,France"),
    SNR("Saint-Nazaire Montoir Airport","Saint-Nazaire,France"),
    ZSE("Pierrefonds Airport","Saint-Pierre,France"),
    LTT("La Môle – Saint-Tropez Airport","Saint-Tropez,France"),
    SYT("Saint-Yan Airport[1] (Charolais Bourgogne Sud Airport)","Saint-Yan,France"),
    SLM("Salamanca Airport","Salamanca,Spain"),
    QSR("Salerno Costa d'Amalfi Airport (Pontecagnano Airport)","Salerno,Italy"),
    SZG("Salzburg Airport","Salzburg,Austria"),
    SMI("Samos International Airport Aristarchos of Samos","Samos,Greece"),
    EAS("San Sebastián Airport","San Sebastián,Spain"),
    SDN("Sandane Airport, Anda","Sandane,Norway"),
    NDY("Sanday Airport","Sanday,United Kingdom"),
    TRF("Sandefjord Airport, Torp","Sandefjord / Oslo,Norway"),
    SSJ("Sandnessjøen Airport, Stokka","Sandnessjøen,Norway"),
    PSH("Sankt Peter-Ording Airport[1]","Sankt Peter-Ording,Germany"),
    SMA("Santa Maria Airport","Santa Maria Island,Portugal"),
    SDR("Santander Airport","Santander,Spain"),
    SCQ("Santiago de Compostela Airport","Santiago de Compostela,Spain"),
    JTR("Santorini (Thira) National Airport","Santorini (Thira),Greece"),
    SJZ("São Jorge Airport","São Jorge Island,Portugal"),
    SOZ("Solenzara Air Base[1]","Sari-Solenzara,France"),
    SUJ("Satu Mare International Airport","Satu Mare,Romania"),
    SVL("Savonlinna Airport[1]","Savonlinna,Finland"),
    SQZ("RAF Scampton[1]","Scampton,United Kingdom"),
    WBG("Schleswig Air Base","Schleswig,Germany"),
    SZW("Schwerin-Parchim International Airport","Schwerin,Germany"),
    SJY("Seinäjoki Airport","Seinäjoki,Finland"),
    SVQ("Seville Airport","Seville,Spain"),
    SNN("Shannon Airport","Shannon,Ireland"),
    LSI("Sumburgh Airport","Shetland Islands,United Kingdom"),
    ESH("Shoreham Airport (Brighton City Airport)","Shoreham-by-Sea,United Kingdom"),
    SQQ("Šiauliai International Airport","Šiauliai,Lithuania"),
    SBZ("Sibiu International Airport","Sibiu,Romania"),
    SGE("Siegerland Airport","Siegen,Germany"),
    SAY("Siena–Ampugnano Airport","Siena,Italy"),
    SLS("Silistra Airfield","Silistra,Bulgaria"),
    CNL("Sindal Airport","Sindal,Denmark"),
    SIE("Sines Airport[1]","Sines,Portugal"),
    SIR("Sion Airport","Sion,Switzerland"),
    JSH("Sitia Public Airport","Sitia,Greece"),
    SFT("Skellefteå Airport","Skellefteå,Sweden"),
    JSI("Skiathos Island National Airport","Skiathos,Greece"),
    SKE("Skien Airport, Geiteryggen","Skien,Norway"),
    SQW("Skive Airport","Skive,Denmark"),
    STA("Stauning Vestjylland Airport","Skjern,Denmark"),
    KVB("Skövde Airport","Skövde,Sweden"),
    SKU("Skyros Island National Airport","Skyros,Greece"),
    SLD("Sliač Airport","Sliač,Slovakia"),
    SXL("Sligo Airport","Sligo,Ireland"),
    SOT("Sodankylä Airfield[1]","Sodankylä,Finland"),
    SOO("Söderhamn Airport[1] (Helsinge Airport)","Söderhamn,Sweden"),
    SOF("Sofia Airport","Sofia,Bulgaria"),
    SOG("Sogndal Airport, Haukåsen","Sogndal,Norway"),
    SGD("Sønderborg Airport","Sønderborg,Denmark"),
    SOJ("Sørkjosen Airport","Sørkjosen,Norway"),
    SOU("Southampton Airport","Southampton,United Kingdom"),
    SPM("Spangdahlem Air Base","Spangdahlem,Germany"),
    SPJ("Sparti Airport","Sparti (Sparta),Greece"),
    NNR("Connemara Airport","Spiddal,Ireland"),
    SPU("Split Airport","Split,Croatia"),
    ADX("RAF Leuchars","St Andrews,United Kingdom"),
    LEQ("Land's End Airport","St Just,United Kingdom"),
    ISC("St Mary's Airport","St Mary's,United Kingdom"),
    RUN("Roland Garros Airport","St-Denis,France"),
    SMV("Samedan Airport (Engadin Airport)","St. Moritz,Switzerland"),
    SZR("Stara Zagora Airport","Stara Zagora,Bulgaria"),
    SVG("Stavanger Airport, Sola","Stavanger,Norway"),
    ARN("Stockholm Arlanda Airport","Stockholm,Sweden"),
    NYO("Stockholm Skavsta Airport","Stockholm / Nyköping,Sweden"),
    VST("Stockholm Västerås Airport","Stockholm / Västerås,Sweden"),
    SKN("Stokmarknes Airport, Skagen","Stokmarknes,Norway"),
    SRP("Stord Airport, Sørstokken","Stord,Norway"),
    SYY("Stornoway Airport","Stornoway,United Kingdom"),
    SQO("Storuman Airport[1]","Storuman,Sweden"),
    BBH("Stralsund–Barth Airport","Stralsund / Barth,Germany"),
    SXB("Strasbourg Airport","Strasbourg,France"),
    RBM("Straubing Wallmühle Airport","Straubing,Germany"),
    SOY("Stronsay Airport","Stronsay,United Kingdom"),
    STR("Stuttgart Airport","Stuttgart,Germany"),
    SCV("Suceava International Airport (Ștefan cel Mare Int'l)","Suceava,Romania"),
    SDL("Sundsvall-Timrå Airport (Midlanda Airport)","Sundsvall / Härnösand,Sweden"),
    EVG("Sveg Airport","Sveg,Sweden"),
    SVJ("Svolvær Airport, Helle","Svolvær,Norway"),
    SWS("Swansea Airport","Swansea,United Kingdom"),
    GWT("Sylt Airport (Westerland Airport)","Sylt,Germany"),
    JSY("Syros Island National Airport","Syros,Greece"),
    SZZ("Solidarity Szczecin–Goleniów Airport","Szczecin,Poland"),
    SZY("Olsztyn-Mazury Regional Airport","Szczytno / Olsztyn,Poland"),
    TLL("Tallinn Airport (Lennart Meri Tallinn Airport)","Tallinn,Estonia"),
    TMP("Tampere–Pirkkala Airport","Tampere,Finland"),
    TAR("Taranto-Grottaglie Airport","Taranto,Italy"),
    LDE("Tarbes–Lourdes–Pyrénées Airport","Tarbes / Lourdes,France"),
    TGV("Targovishte Airport[1] (Buhovtsi Airfield)","Targovishte,Bulgaria"),
    TGM("Târgu Mureș International Airport","Târgu Mureș,Romania"),
    TAY("Tartu Airport","Tartu,Estonia"),
    MME("Durham Tees Valley Airport","Teesside,United Kingdom"),
    TFS("Tenerife–South Airport (Reina Sofia Airport)","Tenerife,Spain"),
    TER("Lajes Field","Terceira Island,Portugal"),
    TEV("Teruel Airport[1]","Teruel,Spain"),
    SKG("Thessaloniki Airport Macedonia","Thessaloniki,Greece"),
    TED("Thisted Airport","Thisted,Denmark"),
    TSR("Timișoara Traian Vuia International Airport","Timișoara,Romania"),
    TRE("Tiree Airport","Tiree,United Kingdom"),
    TYF("Torsby Airport[1]","Torsby,Sweden"),
    TTB("Tortolì Airport (Arbatax Airport)","Tortolì,Italy"),
    TLN("Toulon–Hyères Airport (Hyères Le Palyvestre Airport)","Toulon / Hyères,France"),
    TLS("Toulouse–Blagnac Airport","Toulouse,France"),
    TUF("Tours Val de Loire Airport","Tours,France"),
    TNF("Toussus-le-Noble Airport","Toussus-le-Noble,France"),
    TPS("Vincenzo Florio Airport Trapani–Birgi","Trapani,Italy"),
    TSF("Treviso-Sant'Angelo Airport","Treviso / Venice,Italy"),
    TRS("Trieste – Friuli Venezia Giulia Airport (Ronchi dei Legionari Airport)","Trieste,Italy"),
    THN("Trollhättan–Vänersborg Airport","Trollhättan / Vänersborg,Sweden"),
    TOS("Tromsø Airport, Langnes","Tromsø,Norway"),
    TRD("Trondheim Airport, Værnes","Trondheim,Norway"),
    TCE("Tulcea Danube Delta Airport[1]","Tulcea,Romania"),
    TRN("Turin Airport (Caselle Airport)","Turin,Italy"),
    TKU("Turku Airport","Turku,Finland"),
    UDE("Volkel Air Base","Uden,Netherlands"),
    UDN("Campoformido Airport[1]","Udine,Italy"),
    UHE("Kunovice Airport","Uherské Hradiště,Czech Republic"),
    UME("Umeå Airport","Umeå,Sweden"),
    UNT("Unst Airport[1]","Unst,United Kingdom"),
    UPV("RAF Upavon[1]","Upavon,United Kingdom"),
    UTC("Soesterberg Air Base","Utrecht,Netherlands"),
    UTI("Utti Airport","Utti,Finland"),
    VAA("Vaasa Airport","Vaasa,Finland"),
    VDS("Vadsø Airport","Vadsø,Norway"),
    VAF("Valence-Chabeuil Airport","Valence,France"),
    VLC("Valencia Airport","Valencia,Spain"),
    VLL("Valladolid Airport","Valladolid,Spain"),
    VDE("El Hierro Airport[1]","Valverde,Spain"),
    VNE("Meucon Airport","Vannes,France"),
    VAW("Vardø Airport, Svartnes","Vardø,Norway"),
    VRK("Varkaus Airport","Varkaus,Finland"),
    VAR("Varna Airport","Varna,Bulgaria"),
    VVK("Västervik Airport[1]","Västervik,Sweden"),
    VXO("Växjö/Kronoberg Airport","Växjö,Sweden"),
    VCE("Venice Marco Polo Airport","Venice,Italy"),
    VNT("Ventspils International Airport","Ventspils,Latvia"),
    VRN("Verona Villafranca Airport","Verona,Italy"),
    VIC("Vicenza Airport","Vicenza,Italy"),
    VHY("Vichy — Charmeil Airport[1]","Vichy,France"),
    VIE("Vienna International Airport","Vienna,Austria"),
    VGO("Vigo–Peinador Airport","Vigo,Spain"),
    VRL("Vila Real Airport","Vila Real,Portugal"),
    VHM("Vilhelmina Airport","Vilhelmina,Sweden"),
    VNO("Vilnius Airport","Vilnius,Lithuania"),
    VBY("Visby Airport","Visby,Sweden"),
    VSE("Viseu Airport[1]","Viseu,Portugal"),
    VIT("Vitoria Airport","Vitoria-Gasteiz,Spain"),
    VTL("Vittel - Champ-de-Courses Airport[1]","Vittel,France"),
    SKS("Vojens Airport (Skrydstrup Airport)","Vojens,Denmark"),
    VOL("Nea Anchialos National Airport","Volos,Greece"),
    WTN("RAF Waddington[1]","Waddington,United Kingdom"),
    AGE("Wangerooge Airfield","Wangerooge,Germany"),
    WAW("Warsaw Chopin Airport","Warsaw,Poland"),
    WRT("Warton Aerodrome","Warton,United Kingdom"),
    WAT("Waterford Airport","Waterford,Ireland"),
    NRN("Weeze Airport (Niederrhein Airport)","Weeze,Germany"),
    WRY("Westray Airport[1]","Westray,United Kingdom"),
    WHS("Whalsay Airstrip[1]","Whalsay,United Kingdom"),
    WIC("Wick Airport","Wick,United Kingdom"),
    WIE("Wiesbaden Army Airfield","Wiesbaden,Germany"),
    WVN("JadeWeserAirport","Wilhelmshaven,Germany"),
    WFD("Woodford Aerodrome[1]","Woodford,United Kingdom"),
    WRO("Copernicus Airport Wrocław","Wrocław,Poland"),
    OHR("Wyk auf Föhr Airport[1]","Wyk auf Föhr,Germany"),
    QUY("RAF Wyton[1]","Wyton,United Kingdom"),
    JAM("Bezmer Air Base","Yambol,Bulgaria"),
    BBS("Blackbushe Airport","Yateley,United Kingdom"),
    YEO("Royal Naval Air Station Yeovilton","Yeovilton,United Kingdom"),
    YLI("Ylivieska Airfield","Ylivieska,Finland"),
    ZAD("Zadar Airport","Zadar,Croatia"),
    ZAG("Franjo Tuđman Airport","Zagreb,Croatia"),
    ZTH("Zakynthos International Airport (Dionysios SolomosAirport)","Zakynthos,Greece"),
    ZAZ("Zaragoza Airport","Zaragoza,Spain"),
    IEG("Zielona Góra Airport","Zielona Góra,Poland"),
    ILZ("Žilina Airport","Žilina,Slovakia"),
    GTW("Holešov Airport","Zlín,Czech Republic"),
    OBL("Oostmalle Airfield","Zoersel,Belgium"),
    ZRH("Zurich Airport","Zürich,Switzerland"),
    ZQW("Zweibrücken Airport","Zweibrücken,Germany");

    private String airportName;
    private String locationServed;


    Airports(String airportName, String locationServed) {
        this.airportName = airportName;
        this.locationServed = locationServed;
    }

    public String getLocationServed() {
        return locationServed;
    }

    public String getAirportName() {
        return airportName;
    }
}
